/**
 * Voxelscape — an interactive RAYTRACED voxel world you fly through, rendered
 * entirely by Amanatides-Woo DDA ray traversal in a single fullscreen pixel
 * shader on your real GPU, in pure TypeScript. No triangles, no depth buffer,
 * no rasterized geometry — every pixel marches a ray cell-by-cell through a
 * 128x48x128 voxel grid that lives in a StructuredBuffer<uint> on the GPU.
 *
 * The world is procedurally generated on the CPU at startup from a layered
 * value-noise heightmap: a stone base, dirt, a grass surface, sand shores, a
 * sea level filled with water, and scattered trees (trunk + leaf canopy). Each
 * voxel stores a block type; air is 0. The pixel shader casts a primary DDA ray
 * per pixel, derives the hit FACE NORMAL from the last axis it crossed, lights
 * it with a sun (Lambert + sky ambient), fires a short secondary DDA shadow ray
 * to the sun for soft contact shadows, samples neighbor occupancy for cheap
 * ambient occlusion, and fades everything into a sky gradient with a sun disc
 * via exponential distance fog. The camera is passed as four float3 basis
 * vectors (pos / forward / right / up) in a constant buffer — no matrices, so
 * the column-major HLSL trap never applies.
 *
 * Capture mode (DEMO_DURATION_MS>0): a scripted smooth fly-through orbits and
 * bobs over the terrain looking at the horizon, and a couple of timed block
 * edits drop in. The cursor is never touched. Interactive mode (no duration):
 * WASD + space/shift to move, relative mouse-look, left-click to break a block
 * and right-click to place one (a CPU DDA from screen center picks the target),
 * with a GDI HUD showing fps + controls + GPU name.
 *
 * @bun-win32 / engine APIs: createWindow, createDevice, compile,
 * makeVertexShader/makePixelShader, makeConstantBuffer/updateConstantBuffer,
 * makeStructuredBuffer (cpuWritable SRV, initialData seeding), updateDynamicBuffer,
 * setRenderTargets/setViewport/clear/drawFullscreenTriangle, vsSet/psSet, present,
 * comRelease — plus User32 GetDC/GetCursorPos/SetCursorPos/ShowCursor/GetAsyncKeyState
 * and GDI32 CreateFontW/TextOutW for mouse-look + HUD; captureBackBuffer for the
 * gallery screenshot.
 *
 * Run: bun run packages/all/example/voxelscape.ts
 */

import { resolve } from 'node:path';
import { mkdirSync } from 'node:fs';

import { GDI32, User32 } from '../index';

import * as gpu from './_gpu';
import * as hud from './_hud';
import { captureBackBuffer, formatGrid } from './_snapshot';

const WIDTH = 1280;
const HEIGHT = 720;
const TRANSPARENT_BK = 1;

// World dimensions (i = x + z*W + y*W*D).
const W = 128;
const D = 128;
const H = 48;
const SEA_LEVEL = 16;

// Max additive glow points fed to the shader each frame (explosions, fire, lava…).
const GLOW_MAX = 32;

// Block types (0 = air). The single source of truth: the HLSL palette() switch
// is generated by interpolating these same constants, so TS and shader can never
// drift. Ids are stable — never renumber (the property tables below index by id).
export const B_AIR = 0;
export const B_GRASS = 1;
export const B_DIRT = 2;
export const B_STONE = 3;
export const B_SAND = 4;
export const B_WATER = 5;
export const B_WOOD = 6;
export const B_LEAF = 7;
export const B_SNOW = 8;
export const B_GRAVEL = 9;
export const B_TNT = 10;
export const B_LAVA = 11;
export const B_GLOWSTONE = 12;
export const B_PLANK = 13;
export const B_BRICK = 14;
export const B_OBSIDIAN = 15;
export const B_COUNT = 16;

// ── Per-block property tables (indexed by block id, length B_COUNT) ────────────
/** Collides with a physical body. Air, water, and lava are non-solid (pass through). */
export const SOLID: boolean[] = [
  /* 0 air      */ false, /* 1 grass  */ true, /* 2 dirt   */ true, /* 3 stone */ true,
  /* 4 sand     */ true, /* 5 water  */ false, /* 6 wood    */ true, /* 7 leaf  */ true,
  /* 8 snow     */ true, /* 9 gravel */ true, /* 10 tnt    */ true, /* 11 lava */ false,
  /* 12 glowstn */ true, /* 13 plank */ true, /* 14 brick  */ true, /* 15 obsid */ true,
];
/** Settles under gravity like sand (falls + topples). */
export const FALLS: boolean[] = [
  false, false, false, false, true, false, false, false, false, true,
  false, false, false, false, false, false,
];
/** Fluid kind: 0 none, 1 water, 2 lava. */
export const FLUID: number[] = [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0];
/** Ignite/spread weight: 0 inert; higher catches + spreads faster (leaf fastest). */
export const FLAMMABLE: number[] = [
  0, 0, 0, 0, 0, 0, 0.7, 1.0, 0, 0, 0, 0, 0, 0.6, 0, 0,
];
/** Self-emission 0..1 (lit at night; feeds the glow layer). */
export const EMISSIVE: number[] = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1.0, 0.8, 0, 0, 0];
/** Blast resistance 0 (shatters) .. 1 (immune). */
export const BLAST_RESIST: number[] = [
  0, 0.05, 0.1, 0.35, 0.05, 0, 0.12, 0.04, 0.05, 0.1, 0.1, 0, 0.4, 0.12, 0.7, 1.0,
];

/** Does block `b` collide with a physical body? (air/water/lava pass through.) */
export function isSolid(b: number): boolean {
  return SOLID[b] === true;
}

// ── Cellular physics simulation ────────────────────────────────────────────────
// A pure, factory-created world + active-set automaton: falling sand/gravel,
// mass-based water that floods and settles, throttled lava (lava+water → obsidian/
// stone + steam, ignites flammables), a fire overlay, TNT fuses + chain reactions,
// and radial explosions. The game layer drives it via stepTick() and reacts to the
// returned SimEvents (explosions/steam/splashes/extinguished) with FX/audio/debris.
const SIM_TICK_SECONDS = 1 / 20;
const WATER_MAX = 1.0;
const WATER_MIN = 0.045;
const TNT_FUSE = 1.4; // seconds
const TNT_RADIUS = 4.4;
const TNT_POWER = 1.0;
const HDIRS: ReadonlyArray<readonly [number, number]> = [
  [1, 0],
  [-1, 0],
  [0, 1],
  [0, -1],
];
const N6: ReadonlyArray<readonly [number, number, number]> = [
  [1, 0, 0],
  [-1, 0, 0],
  [0, 1, 0],
  [0, -1, 0],
  [0, 0, 1],
  [0, 0, -1],
];

export interface ExplodeResult {
  destroyed: { x: number; y: number; z: number; block: number }[];
  litTNT: number;
}
export interface SimEvents {
  explosions: { x: number; y: number; z: number; power: number; result: ExplodeResult }[];
  steam: { x: number; y: number; z: number }[];
  splashes: { x: number; y: number; z: number }[];
  extinguished: { x: number; y: number; z: number }[];
}
export interface Sim {
  W: number;
  H: number;
  D: number;
  world: Uint32Array;
  water: Float32Array;
  active: Set<number>;
  fuses: Map<number, number>;
  burning: Map<number, number>;
  idx(x: number, y: number, z: number): number;
  inBounds(x: number, y: number, z: number): boolean;
  getBlock(x: number, y: number, z: number): number;
  setBlock(x: number, y: number, z: number, t: number): void;
  wake(x: number, y: number, z: number): void;
  light(x: number, y: number, z: number): void;
  ignite(x: number, y: number, z: number): void;
  explode(x: number, y: number, z: number, radius: number, power: number): ExplodeResult;
  stepTick(budget: number): SimEvents;
}

/** Build a simulation of size SW×SH×SD, optionally seeded with `data` (its buffer is taken over). */
export function createSim(SW: number, SH: number, SD: number, data?: Uint32Array): Sim {
  const world = data ?? new Uint32Array(SW * SH * SD);
  const water = new Float32Array(SW * SH * SD);
  const active = new Set<number>();
  const fuses = new Map<number, number>();
  const burning = new Map<number, number>();
  const SWD = SW * SD;
  let tick = 0;

  const sidx = (x: number, y: number, z: number): number => x + z * SW + y * SWD;
  const inB = (x: number, y: number, z: number): boolean => x >= 0 && y >= 0 && z >= 0 && x < SW && y < SH && z < SD;
  const get = (x: number, y: number, z: number): number => (inB(x, y, z) ? world[sidx(x, y, z)]! : B_AIR);

  const wake = (x: number, y: number, z: number): void => {
    if (inB(x, y, z)) active.add(sidx(x, y, z));
    for (const [dx, dy, dz] of N6) if (inB(x + dx, y + dy, z + dz)) active.add(sidx(x + dx, y + dy, z + dz));
  };

  const set = (x: number, y: number, z: number, t: number): void => {
    if (!inB(x, y, z)) return;
    const i = sidx(x, y, z);
    world[i] = t;
    if (t === B_WATER) {
      if (water[i]! < WATER_MIN) water[i] = WATER_MAX; // placing water = one full cell
    } else {
      water[i] = 0;
    }
    wake(x, y, z);
  };

  // Seed water mass from any pre-filled water (lake/river/sea); leave it OUT of the
  // active set so settled bodies stay inert until an edit/physics event disturbs them.
  if (data) for (let i = 0; i < world.length; i += 1) if (world[i] === B_WATER) water[i] = WATER_MAX;

  const light = (x: number, y: number, z: number): void => {
    if (get(x, y, z) !== B_TNT) return;
    const i = sidx(x, y, z);
    if (!fuses.has(i)) fuses.set(i, TNT_FUSE + Math.random() * 0.5);
  };

  const ignite = (x: number, y: number, z: number): void => {
    if (!inB(x, y, z)) return;
    const i = sidx(x, y, z);
    if (FLAMMABLE[world[i]!]! <= 0 || burning.has(i)) return;
    burning.set(i, 1.4 + 2.2 * FLAMMABLE[world[i]!]! + Math.random() * 0.6);
  };

  const explode = (cx: number, cy: number, cz: number, radius: number, power: number): ExplodeResult => {
    const destroyed: { x: number; y: number; z: number; block: number }[] = [];
    let litTNT = 0;
    const ri = Math.ceil(radius);
    const r2 = radius * radius;
    for (let dy = -ri; dy <= ri; dy += 1) {
      for (let dz = -ri; dz <= ri; dz += 1) {
        for (let dx = -ri; dx <= ri; dx += 1) {
          const d2 = dx * dx + dy * dy + dz * dz;
          if (d2 > r2) continue;
          const x = cx + dx;
          const y = cy + dy;
          const z = cz + dz;
          if (!inB(x, y, z)) continue;
          const b = world[sidx(x, y, z)]!;
          if (b === B_AIR) continue;
          if (b === B_TNT) {
            light(x, y, z); // chain reaction (fused, not destroyed here)
            litTNT += 1;
            continue;
          }
          if (b === B_OBSIDIAN) continue; // immune
          const falloff = 1 - Math.sqrt(d2) / radius; // 1 at center → 0 at rim
          const pDestroy = power * falloff * 1.4 - BLAST_RESIST[b]!;
          if (Math.random() < pDestroy) {
            destroyed.push({ x, y, z, block: b });
            set(x, y, z, B_AIR); // wakes neighbors so sand/water collapse into the crater
          }
        }
      }
    }
    return { destroyed, litTNT };
  };

  // ── Per-cell rules (return true if the cell should stay active) ───────────────
  const fallStep = (x: number, y: number, z: number, i: number, b: number): boolean => {
    if (y <= 0) return false;
    const bi = sidx(x, y - 1, z);
    const bb = world[bi]!;
    if (bb === B_AIR) {
      world[bi] = b;
      world[i] = B_AIR;
      wake(x, y - 1, z);
      wake(x, y, z);
      return true;
    }
    if (bb === B_WATER) {
      // Sink: the solid drops, the displaced water rises into the vacated cell.
      const wm = water[bi]! > 0 ? water[bi]! : WATER_MAX;
      world[bi] = b;
      water[bi] = 0;
      world[i] = B_WATER;
      water[i] = wm;
      wake(x, y - 1, z);
      wake(x, y, z);
      return true;
    }
    return false;
  };

  const waterStep = (x: number, y: number, z: number, i: number): boolean => {
    // Touching lava turns flowing water to stone (+ steam handled by lava side).
    for (const [dx, dy, dz] of N6) {
      if (get(x + dx, y + dy, z + dz) === B_LAVA) {
        world[i] = B_STONE;
        water[i] = 0;
        wake(x, y, z);
        return true;
      }
    }
    let m = water[i]!;
    if (m <= 0) {
      world[i] = B_AIR;
      return false;
    }
    let changed = false;
    // 1. Fall straight down into air/under-filled water.
    if (y > 0) {
      const bi = sidx(x, y - 1, z);
      const bb = world[bi]!;
      if (bb === B_AIR || bb === B_WATER) {
        const room = WATER_MAX - water[bi]!;
        if (room > 1e-3) {
          const t = Math.min(m, room);
          water[bi]! += t;
          m -= t;
          if (world[bi] !== B_WATER) world[bi] = B_WATER;
          wake(x, y - 1, z);
          changed = true;
        }
      }
    }
    // 2. Spread horizontally toward equalization (randomized order kills axis bias).
    if (m > WATER_MIN) {
      const o = (Math.random() * 4) | 0;
      for (let k = 0; k < 4; k += 1) {
        const dir = HDIRS[(o + k) % 4]!;
        const nx = x + dir[0];
        const nz = z + dir[1];
        if (!inB(nx, y, nz)) continue;
        const ni = sidx(nx, y, nz);
        const nb = world[ni]!;
        if (nb !== B_AIR && nb !== B_WATER) continue;
        const diff = m - water[ni]!;
        if (diff > 0.01) {
          const t = diff * 0.25;
          water[ni]! += t;
          m -= t;
          if (world[ni] !== B_WATER) world[ni] = B_WATER;
          wake(nx, y, nz);
          changed = true;
        }
      }
    }
    water[i] = m;
    if (m < WATER_MIN) {
      water[i] = 0;
      world[i] = B_AIR;
      wake(x, y, z);
      return true;
    }
    // Evaporation valve: stranded shallow water above sea level slowly clears.
    if (y > SEA_LEVEL && m < 0.3 && get(x, y - 1, z) !== B_WATER && Math.random() < 0.03) {
      water[i]! -= 0.06;
      changed = true;
    }
    return changed;
  };

  const lavaStep = (x: number, y: number, z: number, i: number, events: SimEvents): boolean => {
    // Lava touching water solidifies to obsidian (+ steam).
    for (const [dx, dy, dz] of N6) {
      if (get(x + dx, y + dy, z + dz) === B_WATER) {
        world[i] = B_OBSIDIAN;
        wake(x, y, z);
        events.steam.push({ x, y, z });
        return true;
      }
    }
    // Ignite adjacent flammables.
    for (const [dx, dy, dz] of N6) ignite(x + dx, y + dy, z + dz);
    const canDown = y > 0 && get(x, y - 1, z) === B_AIR;
    let sideDir: readonly [number, number] | null = null;
    const o = (Math.random() * 4) | 0;
    for (let k = 0; k < 4; k += 1) {
      const dir = HDIRS[(o + k) % 4]!;
      if (get(x + dir[0], y, z + dir[1]) === B_AIR && get(x + dir[0], y - 1, z + dir[1]) === B_AIR) {
        sideDir = dir;
        break;
      }
    }
    // Viscous: only actually flow every 3rd tick.
    if (tick % 3 === 0) {
      if (canDown) {
        world[sidx(x, y - 1, z)] = B_LAVA;
        world[i] = B_AIR;
        wake(x, y - 1, z);
        wake(x, y, z);
        return true;
      }
      if (sideDir) {
        world[sidx(x + sideDir[0], y, z + sideDir[1])] = B_LAVA;
        world[i] = B_AIR;
        wake(x + sideDir[0], y, z + sideDir[1]);
        wake(x, y, z);
        return true;
      }
    }
    return canDown || sideDir !== null; // stay active until it has settled
  };

  const processFuses = (events: SimEvents): void => {
    for (const [fi, tleft] of [...fuses]) {
      const nt = tleft - SIM_TICK_SECONDS;
      if (nt > 0) {
        fuses.set(fi, nt);
        continue;
      }
      fuses.delete(fi);
      const y = (fi / SWD) | 0;
      const rem = fi - y * SWD;
      const z = (rem / SW) | 0;
      const x = rem - z * SW;
      if (world[fi] === B_TNT) {
        world[fi] = B_AIR;
        wake(x, y, z);
        const result = explode(x, y, z, TNT_RADIUS, TNT_POWER);
        events.explosions.push({ x, y, z, power: TNT_POWER, result });
      }
    }
  };

  const processBurning = (events: SimEvents): void => {
    for (const [bi, tleft] of [...burning]) {
      const y = (bi / SWD) | 0;
      const rem = bi - y * SWD;
      const z = (rem / SW) | 0;
      const x = rem - z * SW;
      // Spread to flammable neighbors.
      for (const [dx, dy, dz] of N6) {
        const nb = get(x + dx, y + dy, z + dz);
        if (FLAMMABLE[nb]! > 0 && Math.random() < FLAMMABLE[nb]! * 0.05) ignite(x + dx, y + dy, z + dz);
      }
      const nt = tleft - SIM_TICK_SECONDS;
      if (nt > 0) {
        burning.set(bi, nt);
        continue;
      }
      burning.delete(bi);
      if (FLAMMABLE[world[bi]!]! > 0) {
        world[bi] = B_AIR;
        wake(x, y, z);
        events.extinguished.push({ x, y, z });
      }
    }
  };

  const stepTick = (budget: number): SimEvents => {
    tick += 1;
    const events: SimEvents = { explosions: [], steam: [], splashes: [], extinguished: [] };
    processFuses(events);
    processBurning(events);
    const list = Array.from(active);
    let visited = 0;
    for (const i of list) {
      if (visited >= budget) break;
      if (!active.has(i)) continue;
      visited += 1;
      active.delete(i);
      const y = (i / SWD) | 0;
      const rem = i - y * SWD;
      const z = (rem / SW) | 0;
      const x = rem - z * SW;
      const b = world[i]!;
      let keep = false;
      if (FALLS[b]) keep = fallStep(x, y, z, i, b);
      else if (b === B_WATER) keep = waterStep(x, y, z, i);
      else if (b === B_LAVA) keep = lavaStep(x, y, z, i, events);
      if (keep) active.add(i);
    }
    return events;
  };

  return {
    W: SW,
    H: SH,
    D: SD,
    world,
    water,
    active,
    fuses,
    burning,
    idx: sidx,
    inBounds: inB,
    getBlock: get,
    setBlock: set,
    wake,
    light,
    ignite,
    explode,
    stepTick,
  };
}

// Virtual-key codes for interactive controls.
const VK_W = 0x57;
const VK_A = 0x41;
const VK_S = 0x53;
const VK_DK = 0x44; // D
const VK_SPACE = 0x20;
const VK_SHIFT = 0x10;
const VK_LBUTTON = 0x01;
const VK_RBUTTON = 0x02;
const VK_F = 0x46; // toggle fly/walk

// ── Fullscreen-triangle vertex shader (SV_VertexID, no vertex buffer) ──────────
const VS_SOURCE = `
struct VSOut { float4 pos : SV_Position; float2 uv : TEXCOORD0; };
VSOut main(uint vid : SV_VertexID) {
  VSOut o;
  float2 p = float2((vid << 1) & 2, vid & 2);
  o.uv = p;
  o.pos = float4(p * float2(2.0, -2.0) + float2(-1.0, 1.0), 0.0, 1.0);
  return o;
}
`;

// ── Pixel shader: Amanatides-Woo DDA voxel raytracer ───────────────────────────
const PS_SOURCE = `
cbuffer Frame : register(b0) {
  float2 iResolution;   // 0
  float  iTime;         // 8
  float  iTimeOfDay;    // 12  (0..1 over a day; 0.5 ≈ noon)
  float3 iCamPos;       // 16
  float  iFlash;        // 28  (0..1 explosion white flash)
  float3 iForward;      // 32
  float  iPad2;         // 44
  float3 iRight;        // 48
  float  iPad3;         // 60
  float3 iUp;           // 64
  float  iFov;          // 76
  float3 iSunDir;       // 80
  float  iPad4;         // 92
  int3   iTargetCell;   // 96  (block under the crosshair)
  int    iTargetValid;  // 108
  uint   iGlowCount;    // 112
  float  iPad5a;        // 116
  float  iPad5b;        // 120
  float  iPad5c;        // 124
  float4 iGlow[${GLOW_MAX * 2}]; // 128: per point — [pos.xyz, radius], [color.rgb, intensity]
};

StructuredBuffer<uint> Voxels : register(t0);

static const int WX = ${W};
static const int WZ = ${D};
static const int WY = ${H};

uint sampleVoxel(int x, int y, int z) {
  if (x < 0 || y < 0 || z < 0 || x >= WX || y >= WY || z >= WZ) return 0u;
  return Voxels[x + z * WX + y * WX * WZ];
}

// Hash helpers for procedural grass / leaf / cloud variation.
float hash21(float2 p) {
  p = frac(p * float2(123.34, 456.21));
  p += dot(p, p + 45.32);
  return frac(p.x * p.y);
}
float vnoise2(float2 p) {
  float2 i = floor(p);
  float2 f = frac(p);
  f = f * f * (3.0 - 2.0 * f);
  float a = hash21(i);
  float b = hash21(i + float2(1, 0));
  float c = hash21(i + float2(0, 1));
  float d = hash21(i + float2(1, 1));
  return lerp(lerp(a, b, f.x), lerp(c, d, f.x), f.y);
}
float fbm2(float2 p) {
  float v = 0.0, a = 0.5;
  [unroll] for (int i = 0; i < 4; i++) { v += a * vnoise2(p); p *= 2.02; a *= 0.5; }
  return v;
}

// Per-block base albedo. Block ids are interpolated from the TS B_* constants
// (single source of truth) so the palette can never drift from the simulation.
// cell lets us add tasteful per-voxel color variation (grass tufts, leaf hue, flowers).
float3 blockColor(uint t, float3 cell) {
  if (t == ${B_GRASS}u) {                            // grass: lush, with subtle hue drift + rare flowers
    float h = hash21(cell.xz * 0.7 + cell.y * 0.13);
    float3 g = lerp(float3(0.30, 0.58, 0.20), float3(0.46, 0.70, 0.26), fbm2(cell.xz * 0.35));
    g = lerp(g, float3(0.52, 0.66, 0.22), 0.25 * h);          // dry-grass tint
    if (h > 0.965) g = lerp(g, float3(0.92, 0.82, 0.30), 0.7); // yellow flower speck
    else if (h < 0.022) g = lerp(g, float3(0.86, 0.40, 0.60), 0.6); // pink flower speck
    return g;
  }
  if (t == ${B_DIRT}u) return float3(0.46, 0.32, 0.20) * (0.92 + 0.16 * hash21(cell.xz + cell.y)); // dirt
  if (t == ${B_STONE}u) {                            // stone: cool grey with mossy/strata variation
    float s = fbm2(cell.xz * 0.5 + cell.y * 0.2);
    return lerp(float3(0.36, 0.37, 0.41), float3(0.50, 0.51, 0.54), s);
  }
  if (t == ${B_SAND}u) return lerp(float3(0.78, 0.70, 0.46), float3(0.90, 0.83, 0.60), fbm2(cell.xz * 0.6)); // sand
  if (t == ${B_WATER}u) return float3(0.05, 0.18, 0.30); // water (mostly overridden by surface shading)
  if (t == ${B_WOOD}u) return float3(0.32, 0.21, 0.12) * (0.9 + 0.2 * hash21(cell.xz + cell.y * 3.0)); // wood
  if (t == ${B_LEAF}u) {                             // leaves: dappled canopy greens
    float h = hash21(cell.xz * 1.3 + cell.y * 0.7);
    return lerp(float3(0.13, 0.40, 0.13), float3(0.26, 0.56, 0.20), h);
  }
  if (t == ${B_SNOW}u) return float3(0.92, 0.95, 1.00); // snow
  if (t == ${B_GRAVEL}u) {                           // gravel: speckled grey pebbles
    float h = hash21(cell.xz * 1.7 + cell.y * 0.5);
    float3 base = lerp(float3(0.40, 0.39, 0.37), float3(0.55, 0.53, 0.50), h);
    return base * (0.85 + 0.3 * hash21(cell.xz * 3.1 + cell.y));
  }
  if (t == ${B_TNT}u) {                              // TNT: red casing with a pale label band
    float band = frac(cell.y * 0.5);
    float3 red = float3(0.74, 0.13, 0.10) * (0.9 + 0.18 * hash21(cell.xz + cell.y));
    float3 label = float3(0.86, 0.84, 0.80);
    return lerp(red, label, step(0.35, band) * step(band, 0.5) * 0.6);
  }
  if (t == ${B_LAVA}u) {                             // lava: hot molten crust (emission added in shading)
    float s = fbm2(cell.xz * 0.5 + cell.y * 0.3);
    return lerp(float3(1.50, 0.45, 0.08), float3(0.85, 0.16, 0.02), s);
  }
  if (t == ${B_GLOWSTONE}u) {                        // glowstone: warm glowing crystal (emissive)
    float h = hash21(cell.xz * 1.1 + cell.y * 0.9);
    return lerp(float3(0.95, 0.80, 0.42), float3(1.00, 0.90, 0.58), h);
  }
  if (t == ${B_PLANK}u) {                            // plank: light sawn-wood boards
    float plank = frac(cell.y * 0.5 + cell.x * 0.05);
    float3 wood = lerp(float3(0.62, 0.46, 0.28), float3(0.74, 0.56, 0.36), hash21(cell.xz + cell.y));
    return wood * (0.86 + 0.14 * step(0.5, plank));
  }
  if (t == ${B_BRICK}u) {                            // brick: red brick with light mortar lines
    float mortar = step(0.85, frac(cell.y * 0.5)) + step(0.85, frac(cell.x * 0.5 + cell.y * 0.25));
    return lerp(float3(0.55, 0.22, 0.16), float3(0.80, 0.78, 0.74), saturate(mortar) * 0.5);
  }
  if (t == ${B_OBSIDIAN}u) {                         // obsidian: near-black volcanic glass with a purple sheen
    float h = hash21(cell.xz * 2.3 + cell.y);
    return float3(0.06, 0.045, 0.10) + float3(0.06, 0.02, 0.10) * h;
  }
  return float3(0.5, 0.5, 0.5);
}

// Drifting cumulus clouds painted into the upper sky.
float clouds(float3 rd) {
  if (rd.y < 0.015) return 0.0;
  float2 cp = rd.xz / max(rd.y, 0.04);               // project onto a high plane
  cp += float2(iTime * 0.012, iTime * 0.006);
  float c = fbm2(cp * 1.1);
  c = smoothstep(0.46, 0.86, c);
  return c * saturate(rd.y * 2.2);                    // fade near horizon
}

// Sky / atmosphere: warm golden-hour gradient with a soft sun, glow and clouds.
float3 skyColor(float3 rd, float3 sun) {
  float up = saturate(rd.y * 0.5 + 0.5);
  // Warm hazy band near the horizon grading up into a deep blue zenith.
  float3 horizon = float3(0.92, 0.80, 0.62);
  float3 mid     = float3(0.50, 0.66, 0.86);
  float3 zenith  = float3(0.14, 0.32, 0.66);
  float3 col = lerp(horizon, mid, pow(saturate(rd.y * 1.4 + 0.06), 0.5));
  col = lerp(col, zenith, pow(up, 1.4));
  float sd = saturate(dot(rd, sun));
  // Warm scatter halo around the sun, biased to the horizon. Keep it from blowing
  // out the whole upper sky by using tighter exponents and modest gains.
  col += float3(1.0, 0.55, 0.26) * pow(sd, 5.0) * 0.40;
  col += float3(1.0, 0.78, 0.46) * pow(sd, 40.0) * 0.70;
  col += float3(1.0, 0.94, 0.82) * pow(sd, 2200.0) * 16.0;        // bright sun disc
  // Clouds, lit warm on the sun-facing side.
  float cl = clouds(rd);
  float3 cloudCol = lerp(float3(0.78, 0.80, 0.86), float3(1.0, 0.88, 0.70), saturate(sd * 1.3));
  col = lerp(col, cloudCol, cl * 0.85);
  // Thicken the warm haze right at the horizon line.
  col = lerp(col, float3(0.95, 0.86, 0.72), pow(1.0 - up, 8.0) * 0.45);
  return col;
}

// Amanatides-Woo DDA. Returns 1 if a solid voxel was hit before maxSteps.
// On hit: outCell = the voxel coords, outNormal = the face normal, outBlock = type, outT = ray distance.
bool traceVoxels(float3 ro, float3 rd, int maxSteps, bool skipWater,
                 out int3 outCell, out float3 outNormal, out uint outBlock, out float outT) {
  outCell = int3(0,0,0); outNormal = float3(0,0,0); outBlock = 0u; outT = 0.0;

  int3 cell = int3(floor(ro));
  float3 invd = 1.0 / rd;
  int3 step = int3(rd.x < 0.0 ? -1 : 1, rd.y < 0.0 ? -1 : 1, rd.z < 0.0 ? -1 : 1);

  // Distance (in t) to the next grid line on each axis.
  float3 tDelta = abs(invd);
  float3 nextEdge = float3(step.x > 0 ? float(cell.x + 1) : float(cell.x),
                           step.y > 0 ? float(cell.y + 1) : float(cell.y),
                           step.z > 0 ? float(cell.z + 1) : float(cell.z));
  float3 tMax = (nextEdge - ro) * invd;

  float3 normal = float3(0,0,0);
  float t = 0.0;
  [loop]
  for (int i = 0; i < maxSteps; i++) {
    uint b = sampleVoxel(cell.x, cell.y, cell.z);
    if (b != 0u && !(skipWater && b == ${B_WATER}u)) {
      outCell = cell; outNormal = normal; outBlock = b; outT = t;
      return true;
    }
    // Advance to the nearest axis plane.
    if (tMax.x < tMax.y && tMax.x < tMax.z) {
      cell.x += step.x; t = tMax.x; tMax.x += tDelta.x; normal = float3(-step.x, 0, 0);
    } else if (tMax.y < tMax.z) {
      cell.y += step.y; t = tMax.y; tMax.y += tDelta.y; normal = float3(0, -step.y, 0);
    } else {
      cell.z += step.z; t = tMax.z; tMax.z += tDelta.z; normal = float3(0, 0, -step.z);
    }
    // Leaving the vertical slab downward = sky below; bail early.
    if (cell.y < -1 && step.y < 0) break;
    if (cell.y > WY + 1 && step.y > 0) break;
  }
  return false;
}

// Longer DDA shadow ray toward the sun. Averages two slightly jittered rays for a
// soft-but-defined penumbra, and returns a low visibility in shadow (crisp contact
// shadows rather than a washed half-tone). dither decorrelates the jitter per pixel.
float shadowRay(float3 ro, float3 rd, float dither) {
  float3 t1 = normalize(cross(rd, float3(0.0, 1.0, 0.0)) + float3(1e-3, 0.0, 0.0));
  float3 t2 = cross(rd, t1);
  float vis = 0.0;
  [unroll] for (int s = 0; s < 2; s++) {
    float a = (dither + float(s) * 0.5) * 6.2831853;
    float2 off = float2(cos(a), sin(a)) * 0.013;
    float3 jd = normalize(rd + t1 * off.x + t2 * off.y);
    int3 c; float3 n; uint b; float tt;
    // Nearer occluders cast a harder (darker) shadow; far ones soften slightly.
    vis += traceVoxels(ro, jd, 80, true, c, n, b, tt) ? lerp(0.10, 0.32, saturate(tt / 28.0)) : 1.0;
  }
  return vis * 0.5;
}

// Does (x,y,z) occlude ambient light? (Air and water do not.)
bool aoSolid(int x, int y, int z) {
  uint b = sampleVoxel(x, y, z);
  return b != 0u && b != ${B_WATER}u;
}

// Smooth (per-corner) ambient occlusion — classic Minecraft "smooth lighting".
// Computes a vertex-AO brightness at each of the face's 4 corners from its 2 edge
// neighbors + diagonal, then bilinearly interpolates across the face by the in-face
// UV, giving a smooth crevice/edge gradient instead of a flat per-face value.
float smoothAO(int3 cell, float3 n, float3 hitPos) {
  float3 upv = abs(n.y) > 0.5 ? float3(0, 0, 1) : float3(0, 1, 0);
  int3 t1 = int3(round(cross(n, upv)));
  int3 t2 = int3(round(cross(n, float3(t1))));
  int3 base = cell + int3(round(n));            // the air cell in front of the face
  float corners[4];
  int ci = 0;
  [unroll] for (int j = -1; j <= 1; j += 2) {
    [unroll] for (int i = -1; i <= 1; i += 2) {
      bool s1 = aoSolid(base.x + i * t1.x, base.y + i * t1.y, base.z + i * t1.z);
      bool s2 = aoSolid(base.x + j * t2.x, base.y + j * t2.y, base.z + j * t2.z);
      bool cc = aoSolid(base.x + i * t1.x + j * t2.x, base.y + i * t1.y + j * t2.y, base.z + i * t1.z + j * t2.z);
      float vert = (s1 && s2) ? 0.0 : (3.0 - (float(s1) + float(s2) + float(cc)));
      corners[ci++] = lerp(0.38, 1.0, vert / 3.0); // fully-occluded corner = 0.38
    }
  }
  float3 fp = hitPos - (float3(cell) + 0.5);
  float u = saturate(dot(fp, float3(t1)) + 0.5);  // 0 at -t1 edge, 1 at +t1 edge
  float v = saturate(dot(fp, float3(t2)) + 0.5);
  float a = lerp(corners[0], corners[1], u);      // v = 0 edge (j = -1)
  float b = lerp(corners[2], corners[3], u);      // v = 1 edge (j = +1)
  return lerp(a, b, v);
}

float4 main(float4 fragPos : SV_Position, float2 uv : TEXCOORD0) : SV_Target {
  float2 res = max(iResolution, float2(1.0, 1.0));
  float2 p = (fragPos.xy * 2.0 - res) / res.y;
  p.y = -p.y;

  float3 rd = normalize(p.x * iRight + p.y * iUp + iFov * iForward);
  float3 ro = iCamPos;
  float3 sun = normalize(iSunDir);

  // Warm directional sun color + cool-ish sky fill, golden-hour graded.
  float3 sunCol = float3(1.55, 1.16, 0.78);
  float3 sky = skyColor(rd, sun);

  int3 cell; float3 n; uint block; float t;
  bool hit = traceVoxels(ro, rd, 320, false, cell, n, block, t);

  float3 col = sky;
  if (hit) {
    float3 hitPos = ro + rd * t;
    float3 albedo = blockColor(block, float3(cell));

    // Subtle per-voxel value variation so faces don't look perfectly flat.
    float vh = frac(sin(dot(float3(cell), float3(12.9898, 78.233, 37.719))) * 43758.5453);
    albedo *= 0.93 + 0.10 * vh;

    // Lighting. Per-face directional weighting (Minecraft-style) makes cubes read
    // crisply even in flat light: bright tops, graded sides, dark undersides.
    float face = (n.y > 0.5) ? 1.0
               : (n.y < -0.5) ? 0.5
               : (abs(n.x) > 0.5 ? (n.x > 0.0 ? 0.82 : 0.66)
                                 : (n.z > 0.0 ? 0.76 : 0.70));
    float ndl = saturate(dot(n, sun));
    float dither = hash21(fragPos.xy + iTime * 37.0);
    float sh = (ndl > 0.0) ? shadowRay(hitPos + n * 0.03, sun, dither) : 0.0;
    float ao = smoothAO(cell, n, hitPos);

    // Cooler, dimmer hemispheric sky ambient so the warm sun defines form (less wash).
    float3 skyAmbCol = lerp(float3(0.09, 0.11, 0.16), float3(0.32, 0.39, 0.52), saturate(n.y * 0.5 + 0.5));
    // Warm bounce/back-fill from the sunlit ground onto side faces.
    float bounce = saturate(dot(n, normalize(float3(-sun.x, 0.12, -sun.z)))) * 0.14;
    float3 lit = albedo * face * (skyAmbCol + sunCol * 2.05 * ndl * sh + bounce * float3(0.40, 0.34, 0.24)) * ao;

    if (block == ${B_WATER}u) {
      // ── Water surface: real raytraced reflection + depth-tinted refraction + foam.
      // Crisp ripples: two directional waves + fbm chop, normal from the analytic gradient.
      float2 wp = hitPos.xz;
      float2 k1 = float2(0.90, 0.55); float A1 = 0.5;
      float2 k2 = float2(-0.50, 1.00); float A2 = 0.4;
      float ph1 = dot(wp, k1) + iTime * 1.7;
      float ph2 = dot(wp, k2) - iTime * 1.3;
      float2 dh = A1 * k1 * cos(ph1) + A2 * k2 * cos(ph2);
      float2 wc = wp * 1.8 + iTime * 0.35;
      dh += 0.6 * float2(fbm2(wc + float2(0.12, 0.0)) - fbm2(wc - float2(0.12, 0.0)),
                         fbm2(wc + float2(0.0, 0.12)) - fbm2(wc - float2(0.0, 0.12)));
      float3 wn = normalize(float3(-dh.x * 0.45, 1.0, -dh.y * 0.45));

      // Reflection: trace the ACTUAL world along the reflected ray (hills, trees, sky).
      float3 refl = reflect(rd, wn);
      refl.y = max(refl.y, 0.015);
      float3 reflCol;
      {
        int3 rc; float3 rn; uint rb; float rt;
        if (traceVoxels(hitPos + wn * 0.06 + refl * 0.05, refl, 72, true, rc, rn, rb, rt)) {
          float3 ra = blockColor(rb, float3(rc));
          float rndl = saturate(dot(rn, sun));
          reflCol = ra * (0.28 + 0.95 * rndl);          // cheap lit reflection of terrain
        } else {
          reflCol = skyColor(refl, sun);
        }
      }

      // Depth: probe straight down to the floor for depth-based color + see-through bottom.
      float3 bottomCol = float3(0.06, 0.20, 0.24);
      int depth = 24;
      [loop] for (int d = 0; d < 24; d++) {
        uint bb = sampleVoxel(cell.x, cell.y - 1 - d, cell.z);
        if (bb != 0u && bb != ${B_WATER}u) { bottomCol = blockColor(bb, float3(cell.x, cell.y - 1 - d, cell.z)); depth = d; break; }
      }
      float depthN = saturate(float(depth) / 6.0);
      float3 shallowTint = float3(0.10, 0.42, 0.46);
      float3 deepTint    = float3(0.02, 0.13, 0.19);
      float3 waterTint = lerp(shallowTint, deepTint, depthN);
      // See the sandy/stony bottom through shallow water; fade to water color with depth.
      float3 refrCol = lerp(bottomCol * float3(0.55, 0.80, 0.92), waterTint, saturate(depthN * 1.5 + 0.18));
      refrCol *= (0.5 + 0.5 * sh);

      // Fresnel mix refraction (looking down) vs reflection (grazing).
      float fres = lerp(0.03, 1.0, pow(saturate(1.0 - dot(-rd, wn)), 5.0));
      lit = lerp(refrCol, reflCol, fres);

      // Foam: white at the shoreline (shallow) and on the brightest ripple crests.
      float crest = smoothstep(0.6, 1.0, (sin(ph1) * 0.5 + sin(ph2) * 0.5) * 0.5 + 0.5);
      float shoreFoam = smoothstep(2.2, 0.0, float(depth));
      lit = lerp(lit, float3(0.95, 0.97, 1.0), saturate(shoreFoam * 0.55 + crest * shoreFoam * 0.4 + crest * 0.06));

      // Sharp sun glint + a shimmering reflection road toward the sun.
      float3 hh = normalize(sun - rd);
      lit += sunCol * pow(saturate(dot(wn, hh)), 220.0) * 2.4;
      lit += float3(1.0, 0.82, 0.55) * pow(saturate(dot(refl, sun)), 28.0) * 0.5;
    } else {
      // Crisp specular highlight on snow only.
      if (block == ${B_SNOW}u) {
        float3 h = normalize(sun - rd);
        float spec = pow(saturate(dot(n, h)), 28.0);
        lit += float3(1.0, 0.97, 0.88) * spec * 0.45 * sh;
      } else if (block == ${B_LAVA}u) {
        // Molten self-emission — pulses gently, brighter at night.
        float pulse = 0.85 + 0.15 * sin(iTime * 2.3 + dot(float3(cell), float3(1.7, 0.3, 1.1)));
        lit += float3(2.0, 0.72, 0.16) * pulse * (1.0 + (1.0 - iTimeOfDay) * 0.6);
      } else if (block == ${B_GLOWSTONE}u) {
        lit += float3(1.05, 0.86, 0.46) * (0.9 + (1.0 - iTimeOfDay) * 0.7);
      }
    }

    // Targeted-block selection outline (Minecraft-style dark frame on the aimed face).
    if (iTargetValid != 0 && cell.x == iTargetCell.x && cell.y == iTargetCell.y && cell.z == iTargetCell.z) {
      float3 an = abs(n);
      float3 fpc = hitPos - (float3(cell) + 0.5);
      float2 uv2 = an.y > 0.5 ? fpc.xz : (an.x > 0.5 ? fpc.zy : fpc.xy);
      float edge = max(abs(uv2.x), abs(uv2.y));
      lit = lerp(lit, lit * 0.2, smoothstep(0.4, 0.5, edge) * 0.85);
    }

    col = lit;

    // ── Atmospheric aerial perspective: warm haze accumulates with distance and
    // brightens toward the sun (in-scattering), so far hills melt into golden air.
    // Kept gentle so foreground voxels stay crisp; only the deep distance softens.
    float fog = 1.0 - exp(-max(0.0, t - 22.0) * 0.0062);
    float sunAmt = saturate(dot(rd, sun));
    float3 hazeCol = lerp(sky, float3(1.0, 0.80, 0.55), pow(sunAmt, 4.0) * 0.35);
    col = lerp(col, hazeCol, saturate(fog));
  }

  // ── Volumetric god-rays: march a few cheap samples along the eye ray and add
  // glow where the path toward the sun is unoccluded (sunlight in the haze).
  // Tight angular falloff so it only blooms right around the sun, not the whole frame.
  {
    float sunAmt = saturate(dot(rd, sun));
    float godStrength = pow(sunAmt, 9.0);
    if (godStrength > 0.002) {
      float acc = 0.0;
      float dither = hash21(fragPos.xy);
      [unroll] for (int gi = 0; gi < 6; gi++) {
        float gt = (float(gi) + dither) * 5.0 + 1.0;
        float3 sp = ro + rd * gt;
        int3 sc; float3 sn; uint sb; float st;
        // Is this sample point lit by the sun? short shadow probe.
        if (!traceVoxels(sp, sun, 22, true, sc, sn, sb, st)) acc += 1.0;
      }
      acc /= 6.0;
      col += float3(1.0, 0.70, 0.40) * acc * godStrength * 0.30;
    }
  }

  // ── Additive glow-point layer (explosions, fireballs, fire, lava, fuses, steam) ──
  // Each point glows into the air with a soft gaussian, depth-occluded by the scene
  // hit distance so glow behind terrain is correctly hidden. Added BEFORE tonemap.
  {
    float sceneT = hit ? t : 1e9;
    [loop] for (uint gi = 0u; gi < iGlowCount; gi++) {
      float4 gA = iGlow[gi * 2u];       // pos.xyz, radius
      float4 gB = iGlow[gi * 2u + 1u];  // color.rgb, intensity
      float gr = max(gA.w, 0.25);
      float s = dot(gA.xyz - ro, rd);
      if (s <= 0.0) continue;
      float occ = saturate((sceneT - s) / max(gr, 1.0) + 0.5); // soft occlusion band
      float d = length((ro + rd * s) - gA.xyz);
      float gauss = exp(-(d * d) / (gr * gr));
      col += gB.rgb * gB.w * gauss * occ / (1.0 + 0.012 * s);
    }
    col = min(col, float3(60.0, 60.0, 60.0)); // keep 32 points from oversaturating
  }

  // Explosion white flash (full-screen, pre-tonemap so it blooms through the filmic curve).
  col += iFlash * float3(1.0, 0.92, 0.82) * 0.55;

  // ── Filmic tonemap (ACES-ish) so highlights glow without hard clipping.
  float exposure = 0.95;
  float3 x = col * exposure;
  col = saturate((x * (2.51 * x + 0.03)) / (x * (2.43 * x + 0.59) + 0.14));
  col = pow(col, 1.0 / 2.2);

  // Soft warm vignette frames the vista.
  float2 q = fragPos.xy / res;
  float vig = pow(16.0 * q.x * q.y * (1.0 - q.x) * (1.0 - q.y), 0.20);
  col *= lerp(0.80, 1.05, vig);
  // Whisper of warm grade in the shadows.
  col = lerp(col, col * float3(1.04, 1.0, 0.94), 0.5);

  return float4(col, 1.0);
}
`;

// ── CPU world generation ────────────────────────────────────────────────────
function idx(x: number, y: number, z: number): number {
  return x + z * W + y * W * D;
}

function lerp01(a: number, b: number, t: number): number {
  return a + (b - a) * t;
}

/** Smooth value noise from a hashed integer lattice with bilinear interpolation. */
function makeNoise2D(seed: number): (x: number, z: number) => number {
  const hash = (xi: number, zi: number): number => {
    let h = (xi * 374761393 + zi * 668265263 + seed * 2147483647) | 0;
    h = (h ^ (h >>> 13)) * 1274126177;
    h = h ^ (h >>> 16);
    return ((h >>> 0) % 100000) / 100000; // 0..1
  };
  const smooth = (a: number, b: number, t: number): number => {
    const s = t * t * (3 - 2 * t);
    return a + (b - a) * s;
  };
  return (x: number, z: number): number => {
    const x0 = Math.floor(x);
    const z0 = Math.floor(z);
    const fx = x - x0;
    const fz = z - z0;
    const v00 = hash(x0, z0);
    const v10 = hash(x0 + 1, z0);
    const v01 = hash(x0, z0 + 1);
    const v11 = hash(x0 + 1, z0 + 1);
    const ix0 = smooth(v00, v10, fx);
    const ix1 = smooth(v01, v11, fx);
    return smooth(ix0, ix1, fz);
  };
}

function generateWorld(): Uint32Array {
  const voxels = new Uint32Array(W * H * D); // zero = all air
  const n1 = makeNoise2D(1337);
  const n2 = makeNoise2D(4242);
  const n3 = makeNoise2D(9001);
  const nRidge = makeNoise2D(5150);
  const nWarp = makeNoise2D(2718);

  const height = new Int32Array(W * D);

  for (let z = 0; z < D; z += 1) {
    for (let x = 0; x < W; x += 1) {
      // Domain-warp the sample point a touch so ridges meander naturally.
      const wx = x + (nWarp(x / 40, z / 40) - 0.5) * 22;
      const wz = z + (nWarp(z / 40 + 5, x / 40 + 5) - 0.5) * 22;

      // Fractal value-noise heightmap (multi-octave).
      let e = 0;
      e += n1(wx / 44, wz / 44) * 1.0;
      e += n2(wx / 19, wz / 19) * 0.5;
      e += n3(wx / 9, wz / 9) * 0.25;
      e /= 1.75; // 0..1

      // Ridged term carves dramatic cliffs and crests for taller, sharper hills.
      const r = 1 - Math.abs(nRidge(wx / 30, wz / 30) * 2 - 1);
      e = e * 0.7 + r * r * 0.45;

      // Shape: gentle valleys, dramatic peaks above the snow line.
      e = Math.pow(Math.max(0, Math.min(1, e)), 1.45);
      let h = Math.floor(5 + e * (H - 8));
      h = Math.max(2, Math.min(H - 2, h));

      // ── Winding river carved through the basin. A meandering channel follows a
      // warped sine; cells near its centerline get gouged down below sea level.
      const riverCenter = D * 0.5 + Math.sin(x / 26) * 16 + (nWarp(x / 30, 7) - 0.5) * 24;
      const riverDist = Math.abs(z - riverCenter);
      const riverWidth = 7 + nWarp(x / 18, 13) * 5;
      if (riverDist < riverWidth) {
        const carve = (1 - riverDist / riverWidth); // 0..1, deepest at center
        const bed = SEA_LEVEL - 3 - Math.floor(carve * 4);
        if (h > bed) h = bed;
        h = Math.max(2, h);
      }

      height[x + z * W] = h;

      for (let y = 0; y <= h; y += 1) {
        let block: number;
        if (y === h) {
          if (h >= H - 8) block = B_SNOW;
          else if (h <= SEA_LEVEL + 1) block = B_SAND;            // beaches/banks
          else block = B_GRASS;
        } else if (y >= h - 3) {
          block = h <= SEA_LEVEL + 2 ? B_SAND : B_DIRT;
        } else {
          block = B_STONE;
        }
        voxels[idx(x, y, z)] = block;
      }

      // Fill water up to sea level over land that sits below it.
      for (let y = h + 1; y <= SEA_LEVEL; y += 1) {
        voxels[idx(x, y, z)] = B_WATER;
      }
    }
  }

  // Scatter trees on grass above the shoreline, with varied canopy shapes/sizes.
  let treeSeed = 24680;
  const rng = (): number => {
    treeSeed = (treeSeed * 1103515245 + 12345) & 0x7fffffff;
    return treeSeed / 0x7fffffff;
  };
  const treeCount = 150;
  for (let tIter = 0; tIter < treeCount; tIter += 1) {
    const tx = 3 + Math.floor(rng() * (W - 6));
    const tz = 3 + Math.floor(rng() * (D - 6));
    const gh = height[tx + tz * W]!;
    if (gh <= SEA_LEVEL + 1 || gh >= H - 10) continue;
    if (voxels[idx(tx, gh, tz)] !== B_GRASS) continue;
    // Skip if right next to water so trees hug the meadows, not the banks.
    const trunk = 4 + Math.floor(rng() * 4);
    for (let y = 1; y <= trunk; y += 1) {
      const yy = gh + y;
      if (yy < H) voxels[idx(tx, yy, tz)] = B_WOOD;
    }
    // Leaf canopy: a rounded blob centered above the trunk top, size varies.
    const top = gh + trunk;
    const r = 2 + Math.floor(rng() * 2); // 2..3
    for (let dy = -1; dy <= 3; dy += 1) {
      const ry = dy <= 0 ? r : Math.max(1, r - dy + 1);
      const rr = ry * ry + (rng() > 0.5 ? 1 : 0);
      for (let dz = -ry; dz <= ry; dz += 1) {
        for (let dx = -ry; dx <= ry; dx += 1) {
          if (dx * dx + dz * dz > rr) continue;
          const lx = tx + dx;
          const ly = top + dy;
          const lz = tz + dz;
          if (lx < 0 || lz < 0 || lx >= W || lz >= D || ly < 0 || ly >= H) continue;
          if (voxels[idx(lx, ly, lz)] === B_AIR) voxels[idx(lx, ly, lz)] = B_LEAF;
        }
      }
    }
  }

  // ── Physics-showcase features: gravel slopes, glowstone veins, lava pools, and
  //    plank shacks to demolish. Reuses the deterministic tree RNG above. ────────
  // Gravel blobs scattered on dry, mid-altitude surface.
  for (let i = 0; i < 40; i += 1) {
    const gx = 3 + Math.floor(rng() * (W - 6));
    const gz = 3 + Math.floor(rng() * (D - 6));
    const gh = height[gx + gz * W]!;
    if (gh <= SEA_LEVEL + 1 || gh >= H - 6) continue;
    const r = 1 + Math.floor(rng() * 2);
    for (let dz = -r; dz <= r; dz += 1) {
      for (let dx = -r; dx <= r; dx += 1) {
        const x = gx + dx;
        const z = gz + dz;
        if (x < 0 || z < 0 || x >= W || z >= D) continue;
        const h = height[x + z * W]!;
        const top = voxels[idx(x, h, z)];
        if (top === B_GRASS || top === B_DIRT) voxels[idx(x, h, z)] = B_GRAVEL;
      }
    }
  }

  // Glowstone veins just beneath the surface (a warm subterranean glint).
  for (let i = 0; i < 24; i += 1) {
    const gx = 2 + Math.floor(rng() * (W - 4));
    const gz = 2 + Math.floor(rng() * (D - 4));
    const gh = height[gx + gz * W]!;
    const gy = Math.max(2, gh - 1 - Math.floor(rng() * 4));
    if (voxels[idx(gx, gy, gz)] === B_STONE) voxels[idx(gx, gy, gz)] = B_GLOWSTONE;
  }

  // A few small lava pools in dry depressions, kept well away from water.
  let pools = 0;
  for (let attempt = 0; attempt < 600 && pools < 3; attempt += 1) {
    const lx = 10 + Math.floor(rng() * (W - 20));
    const lz = 10 + Math.floor(rng() * (D - 20));
    const lh = height[lx + lz * W]!;
    if (lh <= SEA_LEVEL + 3 || lh >= H - 8) continue;
    let nearWater = false;
    for (let dz = -3; dz <= 3 && !nearWater; dz += 1) {
      for (let dx = -3; dx <= 3; dx += 1) {
        const x = lx + dx;
        const z = lz + dz;
        if (x < 0 || z < 0 || x >= W || z >= D) continue;
        if (height[x + z * W]! <= SEA_LEVEL) nearWater = true;
      }
    }
    if (nearWater) continue;
    const r = 2;
    for (let dz = -r; dz <= r; dz += 1) {
      for (let dx = -r; dx <= r; dx += 1) {
        if (dx * dx + dz * dz > r * r + 1) continue;
        const x = lx + dx;
        const z = lz + dz;
        if (x < 0 || z < 0 || x >= W || z >= D) continue;
        const h = height[x + z * W]!;
        voxels[idx(x, h, z)] = B_LAVA;
        if (h - 1 >= 0) voxels[idx(x, h - 1, z)] = B_LAVA;
      }
    }
    pools += 1;
  }

  // A few hollow plank shacks on the meadow — satisfying to blow apart.
  let shacks = 0;
  for (let attempt = 0; attempt < 600 && shacks < 3; attempt += 1) {
    const bx = 12 + Math.floor(rng() * (W - 24));
    const bz = 12 + Math.floor(rng() * (D - 24));
    const bh = height[bx + bz * W]!;
    if (bh <= SEA_LEVEL + 2 || bh >= H - 10) continue;
    if (voxels[idx(bx, bh, bz)] !== B_GRASS) continue;
    const wd = 4;
    const ht = 4;
    for (let dz = 0; dz <= wd; dz += 1) {
      for (let dx = 0; dx <= wd; dx += 1) {
        for (let dy = 1; dy <= ht; dy += 1) {
          const x = bx + dx;
          const z = bz + dz;
          const y = bh + dy;
          if (x >= W || z >= D || y >= H) continue;
          const edge = dx === 0 || dz === 0 || dx === wd || dz === wd;
          const roof = dy === ht;
          const door = dz === 0 && dx === 2 && dy <= 2;
          if ((edge || roof) && !door) voxels[idx(x, y, z)] = B_PLANK;
        }
      }
    }
    shacks += 1;
  }

  return voxels;
}

/** CPU mirror of the shader DDA — picks the targeted/adjacent cell from screen center. */
function pickVoxel(
  voxels: Uint32Array,
  ro: [number, number, number],
  rd: [number, number, number],
  maxSteps: number,
): { hit: boolean; cell: [number, number, number]; prev: [number, number, number] } {
  let cx = Math.floor(ro[0]);
  let cy = Math.floor(ro[1]);
  let cz = Math.floor(ro[2]);
  const sx = rd[0] < 0 ? -1 : 1;
  const sy = rd[1] < 0 ? -1 : 1;
  const sz = rd[2] < 0 ? -1 : 1;
  const idx0 = Math.abs(1 / rd[0]);
  const idy0 = Math.abs(1 / rd[1]);
  const idz0 = Math.abs(1 / rd[2]);
  let tmx = ((sx > 0 ? cx + 1 : cx) - ro[0]) / rd[0];
  let tmy = ((sy > 0 ? cy + 1 : cy) - ro[1]) / rd[1];
  let tmz = ((sz > 0 ? cz + 1 : cz) - ro[2]) / rd[2];
  let px = cx;
  let py = cy;
  let pz = cz;
  for (let i = 0; i < maxSteps; i += 1) {
    if (cx >= 0 && cy >= 0 && cz >= 0 && cx < W && cy < H && cz < D) {
      const b = voxels[idx(cx, cy, cz)]!;
      if (b !== B_AIR && b !== B_WATER) {
        return { hit: true, cell: [cx, cy, cz], prev: [px, py, pz] };
      }
    }
    px = cx;
    py = cy;
    pz = cz;
    if (tmx < tmy && tmx < tmz) {
      cx += sx;
      tmx += idx0;
    } else if (tmy < tmz) {
      cy += sy;
      tmy += idy0;
    } else {
      cz += sz;
      tmz += idz0;
    }
    if (cy < -2 || cy > H + 2) break;
  }
  return { hit: false, cell: [cx, cy, cz], prev: [px, py, pz] };
}

// ── Swept-AABB physics (pure; shared by the player and all entities) ───────────
export interface MoveResult {
  x: number;
  y: number;
  z: number;
  vx: number;
  vy: number;
  vz: number;
  onGround: boolean;
  hitX: boolean;
  hitY: boolean;
  hitZ: boolean;
}

/**
 * Does the body AABB — centered on (x,z) with width sx,sz, feet at y, height sy —
 * overlap any solid voxel? `sampleSolid` decides per cell (incl. out-of-bounds).
 */
function bodyHitsSolid(
  x: number,
  y: number,
  z: number,
  sx: number,
  sy: number,
  sz: number,
  sampleSolid: (x: number, y: number, z: number) => boolean,
): boolean {
  const x0 = Math.floor(x - sx / 2);
  const x1 = Math.floor(x + sx / 2 - 1e-6);
  const z0 = Math.floor(z - sz / 2);
  const z1 = Math.floor(z + sz / 2 - 1e-6);
  const y0 = Math.floor(y);
  const y1 = Math.floor(y + sy - 1e-6);
  for (let yy = y0; yy <= y1; yy += 1) {
    for (let zz = z0; zz <= z1; zz += 1) {
      for (let xx = x0; xx <= x1; xx += 1) {
        if (sampleSolid(xx, yy, zz)) return true;
      }
    }
  }
  return false;
}

/** Binary-search the farthest clear position from `from` (clear) toward `to`. */
function sweepAxis(blocked: (p: number) => boolean, from: number, to: number): { p: number; hit: boolean } {
  if (!blocked(to)) return { p: to, hit: false };
  let lo = from;
  let hi = to;
  for (let i = 0; i < 12; i += 1) {
    const mid = (lo + hi) * 0.5;
    if (blocked(mid)) hi = mid;
    else lo = mid;
  }
  return { p: lo, hit: true };
}

/**
 * Move a body AABB through the voxel grid with axis-separated swept collision.
 * Resolves X, then Z, then Y; sub-steps so no axis advances more than ~0.4 voxels
 * (anti-tunnelling); auto-climbs ledges up to `stepUp` tall when blocked horizontally
 * (so walking up voxel terrain is smooth); sets `onGround` when downward motion is
 * stopped. Pure: `sampleSolid` is the only world access. Gravity/jump are the caller's.
 */
export function sweptMove(
  px: number,
  py: number,
  pz: number,
  vx: number,
  vy: number,
  vz: number,
  sx: number,
  sy: number,
  sz: number,
  dt: number,
  sampleSolid: (x: number, y: number, z: number) => boolean,
  stepUp: number,
): MoveResult {
  const maxMove = Math.max(Math.abs(vx), Math.abs(vy), Math.abs(vz)) * dt;
  const steps = Math.min(16, Math.max(1, Math.ceil(maxMove / 0.4)));
  const h = dt / steps;
  let x = px;
  let y = py;
  let z = pz;
  let onGround = false;
  let hitX = false;
  let hitY = false;
  let hitZ = false;

  for (let s = 0; s < steps; s += 1) {
    if (vx !== 0) {
      const nx = x + vx * h;
      const r = sweepAxis((p) => bodyHitsSolid(p, y, z, sx, sy, sz, sampleSolid), x, nx);
      if (r.hit) {
        if (
          stepUp > 0 &&
          !bodyHitsSolid(x, y + stepUp, z, sx, sy, sz, sampleSolid) &&
          !bodyHitsSolid(nx, y + stepUp, z, sx, sy, sz, sampleSolid)
        ) {
          x = nx;
          y += stepUp;
        } else {
          x = r.p;
          vx = 0;
          hitX = true;
        }
      } else {
        x = r.p;
      }
    }
    if (vz !== 0) {
      const nz = z + vz * h;
      const r = sweepAxis((p) => bodyHitsSolid(x, y, p, sx, sy, sz, sampleSolid), z, nz);
      if (r.hit) {
        if (
          stepUp > 0 &&
          !bodyHitsSolid(x, y + stepUp, z, sx, sy, sz, sampleSolid) &&
          !bodyHitsSolid(x, y + stepUp, nz, sx, sy, sz, sampleSolid)
        ) {
          z = nz;
          y += stepUp;
        } else {
          z = r.p;
          vz = 0;
          hitZ = true;
        }
      } else {
        z = r.p;
      }
    }
    if (vy !== 0) {
      const ny = y + vy * h;
      const r = sweepAxis((p) => bodyHitsSolid(x, p, z, sx, sy, sz, sampleSolid), y, ny);
      if (r.hit) {
        if (vy < 0) onGround = true;
        y = r.p;
        vy = 0;
        hitY = true;
      } else {
        y = r.p;
      }
    }
  }
  return { x, y, z, vx, vy, vz, onGround, hitX, hitY, hitZ };
}

function main(): void {
  const win = gpu.createWindow({ title: 'Voxelscape — raytraced voxel world', width: WIDTH, height: HEIGHT, borderless: true });
  const { w: cw, h: ch } = win.clientSize();
  const g = gpu.createDevice(win.hwnd, { width: cw, height: ch });

  // Build the world on the CPU and upload it as a structured buffer SRV.
  const sim = createSim(W, H, D, generateWorld());
  const voxels = sim.world; // authoritative grid (the sim owns + mutates it)
  const voxelBytes = Buffer.from(voxels.buffer, 0, voxels.byteLength);
  const field = gpu.makeStructuredBuffer({ stride: 4, count: W * H * D, srv: true, cpuWritable: true, initialData: voxelBytes });

  /** Block id at (x,y,z), or air outside the world. */
  const voxelAt = (x: number, y: number, z: number): number =>
    x < 0 || y < 0 || z < 0 || x >= W || y >= H || z >= D ? B_AIR : voxels[idx(x, y, z)]!;

  // Compile shaders.
  let vs: bigint;
  let ps: bigint;
  let vsCode: gpu.CompiledShader;
  let psCode: gpu.CompiledShader;
  try {
    vsCode = gpu.compile(VS_SOURCE, 'main', 'vs_5_0');
    psCode = gpu.compile(PS_SOURCE, 'main', 'ps_5_0');
    vs = gpu.makeVertexShader(vsCode);
    ps = gpu.makePixelShader(psCode);
  } catch (err) {
    console.error(String((err as Error).message));
    teardown(1);
    return;
  }

  // Constant buffer (see the HLSL cbuffer Frame layout): camera/sun/time block @0,
  // target cell @96, glow count @112, then GLOW_MAX×2 float4 of glow points @128.
  const CB_SIZE = 128 + GLOW_MAX * 2 * 16; // 1152 bytes (multiple of 16)
  const cb = gpu.makeConstantBuffer(CB_SIZE);
  const cbData = Buffer.alloc(CB_SIZE);

  const samp = gpu.makeSampler(); // unused by the PS but harmless; kept for parity

  // GDI HUD font.
  const hudFont = GDI32.CreateFontW(-18, 0, 0, 0, 600, 0, 0, 0, 0, 0, 0, 4, 0, Buffer.from('Consolas\0', 'utf16le').ptr!);

  // ── Camera state ────────────────────────────────────────────────────────────
  let camX = W * 0.5;
  let camY = SEA_LEVEL + 18;
  let camZ = -10;
  let yaw = 0.0; // around +Y; 0 looks toward +Z
  let pitch = -0.28;

  // ── Player body (walk mode) ───────────────────────────────────────────────────
  const PSX = 0.6; // body half-extents → AABB 0.6 × 1.8 × 0.6
  const PSY = 1.8;
  const PSZ = 0.6;
  const EYE_H = 1.62; // eye height above the feet
  const GRAVITY = 28;
  const JUMP_V = 8.8;
  const WALK_SPEED = 5.6;
  const SPRINT_SPEED = 9.4;
  const STEP_UP = 1.05; // climb a single full block automatically
  // Spawn on solid ground a bit off the central river.
  const spawnX = Math.floor(W * 0.5) + 0.5;
  const spawnZ = Math.floor(D * 0.28) + 0.5;
  let spawnFeet = SEA_LEVEL + 1;
  for (let y = H - 1; y >= 1; y -= 1) {
    if (isSolid(voxelAt(Math.floor(spawnX), y, Math.floor(spawnZ)))) {
      spawnFeet = y + 1;
      break;
    }
  }
  const player: [number, number, number] = [spawnX, spawnFeet + 0.05, spawnZ];
  const pvel: [number, number, number] = [0, 0, 0];
  let onGround = false;
  let flying = false; // interactive starts in walk mode; F toggles free-fly
  let prevF = false;
  // Solid test for body collision: world edges + floor are walls; air/water/lava pass through.
  const solidAt = (x: number, y: number, z: number): boolean => {
    if (x < 0 || z < 0 || x >= W || z >= D) return true;
    if (y < 0) return true;
    if (y >= H) return false;
    return isSolid(voxelAt(x, y, z));
  };
  // Low golden-hour sun sitting just above the horizon so the hero shot frames it
  // over the water with long shadows, warm haze, and god-rays.
  const sun: [number, number, number] = (() => {
    const elev = 0.28; // radians above horizon (low golden-hour, but clearly a disc)
    const azim = 2.55; // compass-ish heading
    return [Math.cos(elev) * Math.sin(azim), Math.sin(elev), Math.cos(elev) * Math.cos(azim)];
  })();

  const durationMs = process.env.DEMO_DURATION_MS ? Number(process.env.DEMO_DURATION_MS) : 0;
  const interactive = durationMs === 0;
  // Debug/verification static camera in capture mode: VOX_CAM="x,y,z,yaw,pitch".
  const camOverride: number[] | null = process.env.VOX_CAM
    ? process.env.VOX_CAM.split(',').map(Number)
    : null;

  // Mouse-look recenter target (screen coords of the window center).
  const centerScr = { x: 0, y: 0 };
  if (interactive) {
    const rect = Buffer.alloc(16);
    User32.GetWindowRect(win.hwnd, rect.ptr!);
    centerScr.x = Math.floor((rect.readInt32LE(0) + rect.readInt32LE(8)) / 2);
    centerScr.y = Math.floor((rect.readInt32LE(4) + rect.readInt32LE(12)) / 2);
    User32.ShowCursor(0);
    User32.SetCursorPos(centerScr.x, centerScr.y);
  }

  // Edge-debounce for click edits.
  let prevLeft = false;
  let prevRight = false;
  const ptBuf = Buffer.alloc(8);

  console.log('Voxelscape — DDA voxel raytracer on the GPU.');
  console.log(`  ${g.driver} · ${g.gpuName}  ·  world ${W}x${H}x${D}`);
  console.log(interactive ? '  WASD move · space/shift up/down · mouse look · LMB break · RMB place · ESC exit.' : `  Scripted fly-through (${durationMs} ms).`);

  const startTime = performance.now();
  let frames = 0;
  let fps = 0;
  let fpsWindowStart = startTime;
  let lastNow = startTime;

  function basis(): { fwd: [number, number, number]; right: [number, number, number]; up: [number, number, number] } {
    const cp = Math.cos(pitch);
    const fwd: [number, number, number] = [Math.sin(yaw) * cp, Math.sin(pitch), Math.cos(yaw) * cp];
    // right = normalize(cross(worldUp, fwd))
    const rx = fwd[2];
    const rz = -fwd[0];
    const rl = Math.hypot(rx, rz) || 1;
    const right: [number, number, number] = [rx / rl, 0, rz / rl];
    // up = cross(fwd, right)
    const up: [number, number, number] = [
      fwd[1] * right[2] - fwd[2] * right[1],
      fwd[2] * right[0] - fwd[0] * right[2],
      fwd[0] * right[1] - fwd[1] * right[0],
    ];
    return { fwd, right, up };
  }

  function reuploadField(): void {
    const buf = Buffer.from(voxels.buffer, 0, voxels.byteLength);
    gpu.updateDynamicBuffer(field.buffer, buf);
  }

  function setBlock(x: number, y: number, z: number, t: number): void {
    sim.setBlock(x, y, z, t); // routes through the sim so edits wake the physics
  }

  function drawHud(): void {
    hud.draw(g, cw, ch, (dc) => {
      const prevFont = GDI32.SelectObject(dc, hudFont);
      GDI32.SetBkMode(dc, TRANSPARENT_BK);
      const line = `Voxelscape · ${fps} fps · ${g.gpuName} · WASD+mouse · LMB break / RMB place`;
      const text = Buffer.from(`${line}\0`, 'utf16le');
      const len = line.length;
      GDI32.SetTextColor(dc, 0x000000);
      GDI32.TextOutW(dc, 19, 19, text.ptr!, len);
      GDI32.SetTextColor(dc, 0x00e8f0ff);
      GDI32.TextOutW(dc, 18, 18, text.ptr!, len);
      GDI32.SelectObject(dc, prevFont);
    });
  }

  const FOV = 1.5;

  // ── Physics ticking (fixed 20 Hz, accumulator-driven; per-tick cell-visit cap) ─
  const PHYS_TICK = 1 / 20;
  const PHYS_BUDGET = 24000;
  let physAccum = 0;
  let editedThisFrame = false;

  // ── FX state: screen-shake, white flash, transient glow effects, day cycle ─────
  let shake = 0;
  let flash = 0;
  let nextBoom = 0.4; // VOX_BOOM repeating-detonation timer (capture-mode verification)
  let timeOfDay = 0.3; // golden hour (Task: day/night animates this)
  interface GlowFx {
    x: number;
    y: number;
    z: number;
    r0: number;
    cr: number;
    cg: number;
    cb: number;
    intensity: number;
    life: number;
    maxLife: number;
  }
  const glowFx: GlowFx[] = [];

  function triggerExplosionFx(ex: number, ey: number, ez: number, power: number): void {
    glowFx.push({ x: ex + 0.5, y: ey + 0.5, z: ez + 0.5, r0: 2.4 * power, cr: 1.8, cg: 0.8, cb: 0.36, intensity: 2.6 * power, life: 0.5, maxLife: 0.5 });
    const dist = Math.hypot(ex - camX, ey - camY, ez - camZ);
    const atten = 1 / (1 + dist * 0.06);
    shake = Math.min(2.4, shake + power * 1.3 * atten);
    flash = Math.min(0.85, flash + power * 0.3 * atten);
  }

  function processSimEvents(ev: SimEvents): void {
    for (const e of ev.explosions) triggerExplosionFx(e.x, e.y, e.z, e.power);
    for (const s of ev.steam) glowFx.push({ x: s.x + 0.5, y: s.y + 0.9, z: s.z + 0.5, r0: 2.0, cr: 1.0, cg: 1.0, cb: 1.0, intensity: 2.2, life: 0.45, maxLife: 0.45 });
  }

  /** Detonate immediately at (x,y,z): carve + spawn FX (used by tools + the cinematic). */
  function detonate(x: number, y: number, z: number, radius: number, power: number): void {
    const result = sim.explode(x, y, z, radius, power);
    processSimEvents({ explosions: [{ x, y, z, power, result }], steam: [], splashes: [], extinguished: [] });
    editedThisFrame = true;
  }

  // Assemble up to GLOW_MAX glow points into the cbuffer (offset 128), nearest-first
  // with transient FX prioritized. Returns the count written.
  const GLOW_BASE = 128;
  interface GlowCand {
    x: number;
    y: number;
    z: number;
    r: number;
    cr: number;
    cg: number;
    cb: number;
    inten: number;
    pri: number;
    d2: number;
  }
  const glowCands: GlowCand[] = [];
  function buildGlows(nowSec: number): number {
    glowCands.length = 0;
    for (const g of glowFx) {
      const k = Math.max(0, g.life / g.maxLife);
      glowCands.push({ x: g.x, y: g.y, z: g.z, r: g.r0 * (1.35 - 0.35 * k), cr: g.cr, cg: g.cg, cb: g.cb, inten: g.intensity * k, pri: 3, d2: 0 });
    }
    for (const fi of sim.fuses.keys()) {
      const y = (fi / (W * D)) | 0;
      const rem = fi - y * W * D;
      const z = (rem / W) | 0;
      const x = rem - z * W;
      const blink = 0.5 + 0.5 * Math.sin(nowSec * 30);
      glowCands.push({ x: x + 0.5, y: y + 0.5, z: z + 0.5, r: 2.0, cr: 2.2, cg: 0.5, cb: 0.12, inten: 1.4 + 2.4 * blink, pri: 2, d2: 0 });
    }
    let bn = 0;
    for (const bi of sim.burning.keys()) {
      if (bn >= 48) break;
      bn += 1;
      const y = (bi / (W * D)) | 0;
      const rem = bi - y * W * D;
      const z = (rem / W) | 0;
      const x = rem - z * W;
      const fl = 0.7 + 0.3 * Math.sin(nowSec * 20 + x * 1.3 + z * 0.7);
      glowCands.push({ x: x + 0.5, y: y + 1.0, z: z + 0.5, r: 1.9, cr: 1.7, cg: 0.62, cb: 0.18, inten: 1.5 * fl, pri: 1, d2: 0 });
    }
    // Nearby emissive blocks (lava/glowstone) via a small local scan.
    const R = 12;
    const ccx = Math.floor(camX);
    const ccy = Math.floor(camY);
    const ccz = Math.floor(camZ);
    for (let yy = Math.max(0, ccy - R); yy <= Math.min(H - 1, ccy + R); yy += 1) {
      for (let zz = Math.max(0, ccz - R); zz <= Math.min(D - 1, ccz + R); zz += 1) {
        for (let xx = Math.max(0, ccx - R); xx <= Math.min(W - 1, ccx + R); xx += 1) {
          const b = voxels[idx(xx, yy, zz)]!;
          if (EMISSIVE[b]! <= 0) continue;
          if (b === B_LAVA) {
            if (voxelAt(xx, yy + 1, zz) !== B_AIR) continue; // only surface lava glows out
            glowCands.push({ x: xx + 0.5, y: yy + 0.95, z: zz + 0.5, r: 2.4, cr: 1.9, cg: 0.7, cb: 0.18, inten: 1.7, pri: 0, d2: 0 });
          } else {
            glowCands.push({ x: xx + 0.5, y: yy + 0.5, z: zz + 0.5, r: 2.6, cr: 1.0, cg: 0.82, cb: 0.42, inten: 1.5, pri: 0, d2: 0 });
          }
        }
      }
    }
    for (const g of glowCands) g.d2 = (g.x - camX) ** 2 + (g.y - camY) ** 2 + (g.z - camZ) ** 2;
    glowCands.sort((a, b) => b.pri - a.pri || a.d2 - b.d2);
    const count = Math.min(GLOW_MAX, glowCands.length);
    for (let i = 0; i < count; i += 1) {
      const g = glowCands[i]!;
      const o = GLOW_BASE + i * 32;
      cbData.writeFloatLE(g.x, o);
      cbData.writeFloatLE(g.y, o + 4);
      cbData.writeFloatLE(g.z, o + 8);
      cbData.writeFloatLE(g.r, o + 12);
      cbData.writeFloatLE(g.cr, o + 16);
      cbData.writeFloatLE(g.cg, o + 20);
      cbData.writeFloatLE(g.cb, o + 24);
      cbData.writeFloatLE(g.inten, o + 28);
    }
    return count;
  }

  while (!win.shouldClose()) {
    win.pump();
    if (win.shouldClose()) break;

    const now = performance.now();
    const dt = Math.min(0.05, (now - lastNow) / 1000);
    lastNow = now;
    const elapsed = (now - startTime) / 1000;
    editedThisFrame = false;
    shake *= Math.exp(-dt * 6);
    flash *= Math.exp(-dt * 5);
    for (let i = glowFx.length - 1; i >= 0; i -= 1) {
      glowFx[i]!.life -= dt;
      if (glowFx[i]!.life <= 0) glowFx.splice(i, 1);
    }

    if (interactive) {
      // ── Relative mouse-look via GetCursorPos diff against the recenter point ──
      if (User32.GetCursorPos(ptBuf.ptr!)) {
        const mx = ptBuf.readInt32LE(0);
        const my = ptBuf.readInt32LE(4);
        yaw += (mx - centerScr.x) * 0.0022;
        pitch -= (my - centerScr.y) * 0.0022;
        pitch = Math.max(-1.45, Math.min(1.45, pitch));
        User32.SetCursorPos(centerScr.x, centerScr.y);
      }

      // ── Fly/walk toggle (F) ────────────────────────────────────────────────
      const fDown = win.keyDown(VK_F);
      if (fDown && !prevF) flying = !flying;
      prevF = fDown;

      const { fwd, right } = basis();
      let mvF = 0;
      let mvR = 0;
      if (win.keyDown(VK_W)) mvF += 1;
      if (win.keyDown(VK_S)) mvF -= 1;
      if (win.keyDown(VK_DK)) mvR += 1;
      if (win.keyDown(VK_A)) mvR -= 1;

      if (flying) {
        // Free-fly: move the eye directly along the look basis (no gravity/collision).
        const speed = (win.keyDown(VK_SHIFT) ? 30 : 15) * dt;
        let mvU = 0;
        if (win.keyDown(VK_SPACE)) mvU += 1;
        if (win.keyDown(VK_SHIFT)) mvU -= 1;
        player[0] += (fwd[0] * mvF + right[0] * mvR) * speed;
        player[1] += (fwd[1] * mvF + mvU) * speed;
        player[2] += (fwd[2] * mvF + right[2] * mvR) * speed;
        pvel[0] = 0;
        pvel[1] = 0;
        pvel[2] = 0;
      } else {
        // Walk: horizontal velocity on the yaw plane + gravity + jump + swim + step-up.
        const fwdH: [number, number] = [Math.sin(yaw), Math.cos(yaw)];
        const spd = win.keyDown(VK_SHIFT) ? SPRINT_SPEED : WALK_SPEED;
        const inWater = voxelAt(Math.floor(player[0]), Math.floor(player[1] + 0.9), Math.floor(player[2])) === B_WATER;
        const inLava = voxelAt(Math.floor(player[0]), Math.floor(player[1] + 0.2), Math.floor(player[2])) === B_LAVA;
        const drag = inWater ? 0.62 : 1.0;
        pvel[0] = (fwdH[0] * mvF + right[0] * mvR) * spd * drag;
        pvel[2] = (fwdH[1] * mvF + right[2] * mvR) * spd * drag;
        pvel[1] -= (inWater ? GRAVITY * 0.28 : GRAVITY) * dt;
        if (inWater) {
          pvel[1] += GRAVITY * 0.2 * dt; // buoyancy
          pvel[1] = Math.max(pvel[1], -4.5); // slow sink
          if (win.keyDown(VK_SPACE)) pvel[1] = 4.2; // swim up
        } else if (onGround && win.keyDown(VK_SPACE)) {
          pvel[1] = JUMP_V; // jump (auto-repeats while held on ground)
        }
        if (inLava) pvel[1] = 9.0; // slapstick pop out of lava
        pvel[1] = Math.max(pvel[1], -55); // terminal velocity
        const res = sweptMove(player[0], player[1], player[2], pvel[0], pvel[1], pvel[2], PSX, PSY, PSZ, dt, solidAt, STEP_UP);
        player[0] = res.x;
        player[1] = res.y;
        player[2] = res.z;
        pvel[0] = res.vx;
        pvel[1] = res.vy;
        pvel[2] = res.vz;
        onGround = res.onGround;
      }
      // Eye follows the body.
      camX = player[0];
      camY = player[1] + EYE_H;
      camZ = player[2];

      // ── Block edit picking from screen center ─────────────────────────────────
      const { fwd: cf } = basis();
      const leftDown = (User32.GetAsyncKeyState(VK_LBUTTON) & 0x8000) !== 0;
      const rightDown = (User32.GetAsyncKeyState(VK_RBUTTON) & 0x8000) !== 0;
      if (leftDown && !prevLeft) {
        const pick = pickVoxel(voxels, [camX, camY, camZ], cf, 64);
        if (pick.hit) {
          setBlock(pick.cell[0], pick.cell[1], pick.cell[2], B_AIR);
          editedThisFrame = true;
        }
      }
      if (rightDown && !prevRight) {
        const pick = pickVoxel(voxels, [camX, camY, camZ], cf, 64);
        if (pick.hit) {
          setBlock(pick.prev[0], pick.prev[1], pick.prev[2], B_STONE);
          editedThisFrame = true;
        }
      }
      prevLeft = leftDown;
      prevRight = rightDown;
    } else if (camOverride) {
      // ── Debug/verification static camera: VOX_CAM="x,y,z,yaw,pitch" ───────────
      camX = camOverride[0]!;
      camY = camOverride[1]!;
      camZ = camOverride[2]!;
      yaw = camOverride[3]!;
      pitch = camOverride[4]!;
    } else {
      // ── Scripted cinematic fly-through (capture mode) ─────────────────────────
      // The shot is timed so the FINAL frame frames the low sun over the river: we
      // glide low across the meadow, descending and turning to face into the light.
      const tt = elapsed;
      const total = Math.max(0.001, durationMs / 1000);
      const u = Math.min(1, tt / total); // 0..1 over the whole take
      const ease = u * u * (3 - 2 * u);
      const cx = W * 0.5;
      const cz = D * 0.5;
      // Sun azimuth: aim the hero frame down that bearing so the sun sits on the
      // horizon over the water for the finale.
      const sunYaw = Math.atan2(sun[0], sun[2]);
      // Position the camera up-sun of the river basin, looking back toward the sun
      // so the river leads the eye to the sun on the horizon. Keep it fairly close
      // and low so foreground blocks read crisply and the sky/sun fill the top.
      const back = 36 - ease * 6;        // distance behind the basin, eases in a bit
      camX = cx - Math.sin(sunYaw) * back + Math.sin(tt * 0.22) * 3;
      camZ = cz - Math.cos(sunYaw) * back + Math.sin(tt * 0.16) * 3;
      // Glide down from a survey altitude to a relaxed elevated vista height.
      camY = SEA_LEVEL + 18 - ease * 5 + Math.sin(tt * 0.55) * 0.8;
      // Hold the heading on the sun, with a slow drift earlier to feel alive.
      yaw = sunYaw + (1 - ease) * -0.28;
      // Tilt down to survey terrain, levelling toward the horizon so sky + sun show.
      pitch = lerp01(-0.34, -0.11, ease) + Math.sin(tt * 0.5) * 0.012;
    }

    // Debug/verification: repeating detonations in capture mode (VOX_BOOM=1).
    if (!interactive && process.env.VOX_BOOM && elapsed > nextBoom) {
      detonate(Math.floor(W * 0.5), SEA_LEVEL + 7, Math.floor(D * 0.5), 6, 1.6);
      nextBoom = elapsed + 0.7;
    }

    // ── Step the physics simulation (fixed timestep) ───────────────────────────
    const wasActive = sim.active.size > 0 || sim.fuses.size > 0 || sim.burning.size > 0;
    physAccum += dt;
    let ticksRun = 0;
    while (physAccum >= PHYS_TICK && ticksRun < 6) {
      processSimEvents(sim.stepTick(PHYS_BUDGET));
      physAccum -= PHYS_TICK;
      ticksRun += 1;
    }
    // Re-upload the grid only when something changed (idle world ⇒ no upload).
    if (wasActive || editedThisFrame) reuploadField();

    // ── Build the constant buffer immediately before the consuming call ─────────
    const { fwd, right, up } = basis();
    // Screen-shake jitters the eye position.
    const ox = shake > 0.001 ? (Math.random() * 2 - 1) * shake * 0.35 : 0;
    const oy = shake > 0.001 ? (Math.random() * 2 - 1) * shake * 0.35 : 0;
    const oz = shake > 0.001 ? (Math.random() * 2 - 1) * shake * 0.35 : 0;
    cbData.writeFloatLE(cw, 0);
    cbData.writeFloatLE(ch, 4);
    cbData.writeFloatLE(elapsed, 8);
    cbData.writeFloatLE(timeOfDay, 12);
    cbData.writeFloatLE(camX + ox, 16);
    cbData.writeFloatLE(camY + oy, 20);
    cbData.writeFloatLE(camZ + oz, 24);
    cbData.writeFloatLE(Math.min(1, flash), 28);
    cbData.writeFloatLE(fwd[0], 32);
    cbData.writeFloatLE(fwd[1], 36);
    cbData.writeFloatLE(fwd[2], 40);
    cbData.writeFloatLE(0, 44);
    cbData.writeFloatLE(right[0], 48);
    cbData.writeFloatLE(right[1], 52);
    cbData.writeFloatLE(right[2], 56);
    cbData.writeFloatLE(0, 60);
    cbData.writeFloatLE(up[0], 64);
    cbData.writeFloatLE(up[1], 68);
    cbData.writeFloatLE(up[2], 72);
    cbData.writeFloatLE(FOV, 76);
    cbData.writeFloatLE(sun[0], 80);
    cbData.writeFloatLE(sun[1], 84);
    cbData.writeFloatLE(sun[2], 88);
    cbData.writeFloatLE(0, 92);
    // Targeted block under the crosshair (interactive only → selection outline).
    const tgt = pickVoxel(voxels, [camX, camY, camZ], fwd, 80);
    if (interactive && tgt.hit) {
      cbData.writeInt32LE(tgt.cell[0], 96);
      cbData.writeInt32LE(tgt.cell[1], 100);
      cbData.writeInt32LE(tgt.cell[2], 104);
      cbData.writeInt32LE(1, 108);
    } else {
      cbData.writeInt32LE(0, 108);
    }
    cbData.writeUInt32LE(buildGlows(elapsed), 112);
    gpu.updateConstantBuffer(cb, cbData);

    gpu.setRenderTargets([g.backBufferRTV]);
    gpu.setViewport(cw, ch);
    gpu.vsSet(vs);
    gpu.psSet(ps, { cb: [cb], srv: [field.srv!] });
    gpu.drawFullscreenTriangle();

    // ── Capture the gallery PNG on the final frame, before present() ────────────
    const lastFrame = durationMs > 0 && now - startTime >= durationMs;
    if (lastFrame) {
      const shotDir = resolve(import.meta.dir, '..', 'screenshots');
      mkdirSync(shotDir, { recursive: true });
      const stats = captureBackBuffer(g, resolve(shotDir, 'voxelscape.png'), { gridW: 48, gridH: 22 });
      console.log(formatGrid(stats));
      console.log(`[shot] ok=${stats.ok} nonBlack=${stats.nonBlackFrac.toFixed(3)} meanLuma=${stats.meanLuma.toFixed(3)} -> ${stats.path}`);
    }

    if (interactive) drawHud();
    g.present(false);

    frames += 1;
    if (now - fpsWindowStart >= 500) {
      fps = Math.round((frames * 1000) / (now - fpsWindowStart));
      frames = 0;
      fpsWindowStart = now;
    }

    if (lastFrame) break;
  }

  console.log(`Voxelscape done · ${fps} fps · ${g.driver} · ${g.gpuName}`);
  teardown(0);

  // ── Teardown ──────────────────────────────────────────────────────────────
  function teardown(code: number): void {
    if (interactive) User32.ShowCursor(1);
    hud.release();
    GDI32.DeleteObject(hudFont);
    comReleaseSafe(samp);
    comReleaseSafe(cb);
    comReleaseSafe(field.srv);
    comReleaseSafe(field.buffer);
    comReleaseSafe(ps);
    comReleaseSafe(vs);
    if (vsCode) gpu.blobRelease(vsCode.blob);
    if (psCode) gpu.blobRelease(psCode.blob);
    comReleaseSafe(g.backBufferRTV);
    comReleaseSafe(g.swapChain);
    comReleaseSafe(g.context);
    comReleaseSafe(g.device);
    win.destroy();
    process.exit(code);
  }
}

function comReleaseSafe(ptr: bigint | undefined): void {
  if (ptr !== undefined && ptr !== 0n) gpu.comRelease(ptr);
}

// Only launch the game when run directly. Importing this module (e.g. from
// voxelscape.logic.test.ts) exposes the pure exports without opening a window.
if (import.meta.main) {
  process.on('SIGINT', () => process.exit(0));
  process.on('uncaughtException', (e) => {
    console.error(e);
    process.exit(1);
  });
  main();
}
