import type { Pointer } from 'bun:ffi';

import type { HANDLE, ULONG } from '@bun-win32/core';
export type { BOOLEAN, LPCVOID, Optional, PBYTE, PULONG, ULONG, USHORT } from '@bun-win32/core';

export enum DECODING_SOURCE {
  DecodingSourceMax = 4,
  DecodingSourceTlg = 3,
  DecodingSourceWbem = 1,
  DecodingSourceWPP = 2,
  DecodingSourceXMLFile = 0,
}

export enum EVENT_FIELD_TYPE {
  EventChannelInformation = 2,
  EventInformationMax = 5,
  EventKeywordInformation = 0,
  EventLevelInformation = 1,
  EventOpcodeInformation = 4,
  EventTaskInformation = 3,
}

export enum MAP_FLAGS {
  EVENTMAP_INFO_FLAG_MANIFEST_BITMAP = 0x0000_0002,
  EVENTMAP_INFO_FLAG_MANIFEST_PATTERNMAP = 0x0000_0004,
  EVENTMAP_INFO_FLAG_MANIFEST_VALUEMAP = 0x0000_0001,
  EVENTMAP_INFO_FLAG_WBEM_BITMAP = 0x0000_0010,
  EVENTMAP_INFO_FLAG_WBEM_FLAG = 0x0000_0020,
  EVENTMAP_INFO_FLAG_WBEM_NO_MAP = 0x0000_0040,
  EVENTMAP_INFO_FLAG_WBEM_VALUEMAP = 0x0000_0008,
}

export enum MAP_VALUETYPE {
  EVENTMAP_ENTRY_VALUETYPE_STRING = 1,
  EVENTMAP_ENTRY_VALUETYPE_ULONG = 0,
}

export enum PAYLOAD_OPERATOR {
  PAYLOADFIELD_BETWEEN = 6,
  PAYLOADFIELD_CONTAINS = 20,
  PAYLOADFIELD_DOESNTCONTAIN = 21,
  PAYLOADFIELD_EQ = 0,
  PAYLOADFIELD_GE = 5,
  PAYLOADFIELD_GT = 3,
  PAYLOADFIELD_INVALID = 32,
  PAYLOADFIELD_IS = 30,
  PAYLOADFIELD_ISNOT = 31,
  PAYLOADFIELD_LE = 2,
  PAYLOADFIELD_LT = 4,
  PAYLOADFIELD_MODULO = 8,
  PAYLOADFIELD_NE = 1,
  PAYLOADFIELD_NOTBETWEEN = 7,
}

export enum PROPERTY_FLAGS {
  PropertyHasCustomSchema = 0x0000_0080,
  PropertyHasTags = 0x0000_0040,
  PropertyParamCount = 0x0000_0004,
  PropertyParamFixedCount = 0x0000_0020,
  PropertyParamFixedLength = 0x0000_0010,
  PropertyParamLength = 0x0000_0002,
  PropertyStruct = 0x0000_0001,
  PropertyWBEMXmlFragment = 0x0000_0008,
}

export enum TDH_CONTEXT_TYPE {
  TDH_CONTEXT_MAXIMUM = 5,
  TDH_CONTEXT_PDB_PATH = 4,
  TDH_CONTEXT_POINTERSIZE = 3,
  TDH_CONTEXT_WPP_GMT = 2,
  TDH_CONTEXT_WPP_TMFFILE = 0,
  TDH_CONTEXT_WPP_TMFSEARCHPATH = 1,
}

export enum TDH_IN_TYPE {
  TDH_INTYPE_ANSICHAR = 307,
  TDH_INTYPE_ANSISTRING = 2,
  TDH_INTYPE_BINARY = 14,
  TDH_INTYPE_BOOLEAN = 13,
  TDH_INTYPE_COUNTEDANSISTRING = 301,
  TDH_INTYPE_COUNTEDSTRING = 300,
  TDH_INTYPE_DOUBLE = 12,
  TDH_INTYPE_FILETIME = 17,
  TDH_INTYPE_FLOAT = 11,
  TDH_INTYPE_GUID = 15,
  TDH_INTYPE_HEXDUMP = 309,
  TDH_INTYPE_HEXINT32 = 20,
  TDH_INTYPE_HEXINT64 = 21,
  TDH_INTYPE_INT16 = 5,
  TDH_INTYPE_INT32 = 7,
  TDH_INTYPE_INT64 = 9,
  TDH_INTYPE_INT8 = 3,
  TDH_INTYPE_MANIFEST_COUNTEDANSISTRING = 23,
  TDH_INTYPE_MANIFEST_COUNTEDBINARY = 25,
  TDH_INTYPE_MANIFEST_COUNTEDSTRING = 22,
  TDH_INTYPE_NONNULLTERMINATEDANSISTRING = 305,
  TDH_INTYPE_NONNULLTERMINATEDSTRING = 304,
  TDH_INTYPE_NULL = 0,
  TDH_INTYPE_POINTER = 16,
  TDH_INTYPE_RESERVED24 = 24,
  TDH_INTYPE_REVERSEDCOUNTEDANSISTRING = 303,
  TDH_INTYPE_REVERSEDCOUNTEDSTRING = 302,
  TDH_INTYPE_SID = 19,
  TDH_INTYPE_SIZET = 308,
  TDH_INTYPE_SYSTEMTIME = 18,
  TDH_INTYPE_UINT16 = 6,
  TDH_INTYPE_UINT32 = 8,
  TDH_INTYPE_UINT64 = 10,
  TDH_INTYPE_UINT8 = 4,
  TDH_INTYPE_UNICODECHAR = 306,
  TDH_INTYPE_UNICODESTRING = 1,
  TDH_INTYPE_WBEMSID = 310,
}

export enum TDH_OUT_TYPE {
  TDH_OUTTYPE_BOOLEAN = 13,
  TDH_OUTTYPE_BYTE = 3,
  TDH_OUTTYPE_CIMDATETIME = 26,
  TDH_OUTTYPE_CODE_POINTER = 37,
  TDH_OUTTYPE_CULTURE_INSENSITIVE_DATETIME = 33,
  TDH_OUTTYPE_DATETIME = 2,
  TDH_OUTTYPE_DATETIME_UTC = 38,
  TDH_OUTTYPE_DOUBLE = 12,
  TDH_OUTTYPE_ERRORCODE = 29,
  TDH_OUTTYPE_ETWTIME = 27,
  TDH_OUTTYPE_FLOAT = 11,
  TDH_OUTTYPE_GUID = 14,
  TDH_OUTTYPE_HEXBINARY = 15,
  TDH_OUTTYPE_HEXINT16 = 17,
  TDH_OUTTYPE_HEXINT32 = 18,
  TDH_OUTTYPE_HEXINT64 = 19,
  TDH_OUTTYPE_HEXINT8 = 16,
  TDH_OUTTYPE_HRESULT = 32,
  TDH_OUTTYPE_INT = 7,
  TDH_OUTTYPE_IPV4 = 23,
  TDH_OUTTYPE_IPV6 = 24,
  TDH_OUTTYPE_JSON = 34,
  TDH_OUTTYPE_LONG = 9,
  TDH_OUTTYPE_NOPRINT = 301,
  TDH_OUTTYPE_NTSTATUS = 31,
  TDH_OUTTYPE_NULL = 0,
  TDH_OUTTYPE_PID = 20,
  TDH_OUTTYPE_PKCS7_WITH_TYPE_INFO = 36,
  TDH_OUTTYPE_PORT = 22,
  TDH_OUTTYPE_REDUCEDSTRING = 300,
  TDH_OUTTYPE_SHORT = 5,
  TDH_OUTTYPE_SOCKETADDRESS = 25,
  TDH_OUTTYPE_STRING = 1,
  TDH_OUTTYPE_TID = 21,
  TDH_OUTTYPE_UNSIGNEDBYTE = 4,
  TDH_OUTTYPE_UNSIGNEDINT = 8,
  TDH_OUTTYPE_UNSIGNEDLONG = 10,
  TDH_OUTTYPE_UNSIGNEDSHORT = 6,
  TDH_OUTTYPE_UTF8 = 35,
  TDH_OUTTYPE_WIN32ERROR = 30,
  TDH_OUTTYPE_XML = 28,
}

export enum TEMPLATE_FLAGS {
  TEMPLATE_CONTROL_GUID = 0x0000_0004,
  TEMPLATE_EVENT_DATA = 0x0000_0001,
  TEMPLATE_USER_DATA = 0x0000_0002,
}

export type LPCGUID = Pointer;
export type LPGUID = Pointer;
export type PBOOLEAN = Pointer;
export type PCEVENT_DESCRIPTOR = Pointer;
export type PEVENT_DESCRIPTOR = Pointer;
export type PEVENT_FILTER_DESCRIPTOR = Pointer;
export type PEVENT_MAP_INFO = Pointer;
export type PEVENT_RECORD = Pointer;
export type PPAYLOAD_FILTER_PREDICATE = Pointer;
export type PPPROVIDER_FILTER_INFO = Pointer;
export type PPROPERTY_DATA_DESCRIPTOR = Pointer;
export type PPROVIDER_ENUMERATION_INFO = Pointer;
export type PPROVIDER_EVENT_INFO = Pointer;
export type PPROVIDER_FIELD_INFOARRAY = Pointer;
export type PPVOID = Pointer;
export type PTDH_CONTEXT = Pointer;
export type PTDH_HANDLE = Pointer;
export type PTRACE_EVENT_INFO = Pointer;
export type PUSHORT = Pointer;
export type PWCHAR = Pointer;
export type PWSTR = Pointer;
export type TDHSTATUS = ULONG;
export type TDH_HANDLE = HANDLE;
export type ULONGLONG = bigint;
