import type { Pointer } from 'bun:ffi';

export type { BOOLEAN, DWORD, HANDLE, HRESULT, LPCVOID, LPCWSTR, Optional, PDWORD, PHANDLE, PVOID, VOID } from '@bun-win32/core';

export const CF_EOF = -1n;
export const CF_MAX_PRIORITY_HINT = 15;
export const CF_MAX_PROVIDER_NAME_LENGTH = 255;
export const CF_MAX_PROVIDER_VERSION_LENGTH = 255;
export const CF_PLACEHOLDER_MAX_FILE_IDENTITY_LENGTH = 4096;
export const CF_REQUEST_KEY_DEFAULT = 0n;

export enum CF_CALLBACK_CANCEL_FLAGS {
  CF_CALLBACK_CANCEL_FLAG_IO_ABORTED = 0x0000_0002,
  CF_CALLBACK_CANCEL_FLAG_IO_TIMEOUT = 0x0000_0001,
  CF_CALLBACK_CANCEL_FLAG_NONE = 0x0000_0000,
}

export enum CF_CALLBACK_CLOSE_COMPLETION_FLAGS {
  CF_CALLBACK_CLOSE_COMPLETION_FLAG_DELETED = 0x0000_0001,
  CF_CALLBACK_CLOSE_COMPLETION_FLAG_NONE = 0x0000_0000,
}

export enum CF_CALLBACK_DEHYDRATE_COMPLETION_FLAGS {
  CF_CALLBACK_DEHYDRATE_COMPLETION_FLAG_BACKGROUND = 0x0000_0001,
  CF_CALLBACK_DEHYDRATE_COMPLETION_FLAG_DEHYDRATED = 0x0000_0002,
  CF_CALLBACK_DEHYDRATE_COMPLETION_FLAG_NONE = 0x0000_0000,
}

export enum CF_CALLBACK_DEHYDRATE_FLAGS {
  CF_CALLBACK_DEHYDRATE_FLAG_BACKGROUND = 0x0000_0001,
  CF_CALLBACK_DEHYDRATE_FLAG_NONE = 0x0000_0000,
}

export enum CF_CALLBACK_DEHYDRATION_REASON {
  CF_CALLBACK_DEHYDRATION_REASON_NONE = 0,
  CF_CALLBACK_DEHYDRATION_REASON_SYSTEM_INACTIVITY = 3,
  CF_CALLBACK_DEHYDRATION_REASON_SYSTEM_LOW_SPACE = 2,
  CF_CALLBACK_DEHYDRATION_REASON_SYSTEM_OS_UPGRADE = 4,
  CF_CALLBACK_DEHYDRATION_REASON_USER_MANUAL = 1,
}

export enum CF_CALLBACK_DELETE_COMPLETION_FLAGS {
  CF_CALLBACK_DELETE_COMPLETION_FLAG_NONE = 0x0000_0000,
}

export enum CF_CALLBACK_DELETE_FLAGS {
  CF_CALLBACK_DELETE_FLAG_IS_DIRECTORY = 0x0000_0001,
  CF_CALLBACK_DELETE_FLAG_IS_UNDELETE = 0x0000_0002,
  CF_CALLBACK_DELETE_FLAG_NONE = 0x0000_0000,
}

export enum CF_CALLBACK_FETCH_DATA_FLAGS {
  CF_CALLBACK_FETCH_DATA_FLAG_EXPLICIT_HYDRATION = 0x0000_0002,
  CF_CALLBACK_FETCH_DATA_FLAG_NONE = 0x0000_0000,
  CF_CALLBACK_FETCH_DATA_FLAG_RECOVERY = 0x0000_0001,
}

export enum CF_CALLBACK_FETCH_PLACEHOLDERS_FLAGS {
  CF_CALLBACK_FETCH_PLACEHOLDERS_FLAG_NONE = 0x0000_0000,
}

export enum CF_CALLBACK_OPEN_COMPLETION_FLAGS {
  CF_CALLBACK_OPEN_COMPLETION_FLAG_NONE = 0x0000_0000,
  CF_CALLBACK_OPEN_COMPLETION_FLAG_PLACEHOLDER_UNKNOWN = 0x0000_0001,
  CF_CALLBACK_OPEN_COMPLETION_FLAG_PLACEHOLDER_UNSUPPORTED = 0x0000_0002,
}

export enum CF_CALLBACK_RENAME_COMPLETION_FLAGS {
  CF_CALLBACK_RENAME_COMPLETION_FLAG_NONE = 0x0000_0000,
}

export enum CF_CALLBACK_RENAME_FLAGS {
  CF_CALLBACK_RENAME_FLAG_IS_DIRECTORY = 0x0000_0001,
  CF_CALLBACK_RENAME_FLAG_NONE = 0x0000_0000,
  CF_CALLBACK_RENAME_FLAG_SOURCE_IN_SCOPE = 0x0000_0002,
  CF_CALLBACK_RENAME_FLAG_TARGET_IN_SCOPE = 0x0000_0004,
}

export enum CF_CALLBACK_TYPE {
  CF_CALLBACK_TYPE_CANCEL_FETCH_DATA = 2,
  CF_CALLBACK_TYPE_CANCEL_FETCH_PLACEHOLDERS = 4,
  CF_CALLBACK_TYPE_FETCH_DATA = 0,
  CF_CALLBACK_TYPE_FETCH_PLACEHOLDERS = 3,
  CF_CALLBACK_TYPE_NONE = 0xffff_ffff,
  CF_CALLBACK_TYPE_NOTIFY_DEHYDRATE = 7,
  CF_CALLBACK_TYPE_NOTIFY_DEHYDRATE_COMPLETION = 8,
  CF_CALLBACK_TYPE_NOTIFY_DELETE = 9,
  CF_CALLBACK_TYPE_NOTIFY_DELETE_COMPLETION = 10,
  CF_CALLBACK_TYPE_NOTIFY_FILE_CLOSE_COMPLETION = 6,
  CF_CALLBACK_TYPE_NOTIFY_FILE_OPEN_COMPLETION = 5,
  CF_CALLBACK_TYPE_NOTIFY_RENAME = 11,
  CF_CALLBACK_TYPE_NOTIFY_RENAME_COMPLETION = 12,
  CF_CALLBACK_TYPE_VALIDATE_DATA = 1,
}

export enum CF_CALLBACK_VALIDATE_DATA_FLAGS {
  CF_CALLBACK_VALIDATE_DATA_FLAG_EXPLICIT_HYDRATION = 0x0000_0002,
  CF_CALLBACK_VALIDATE_DATA_FLAG_NONE = 0x0000_0000,
}

export enum CF_CONNECT_FLAGS {
  CF_CONNECT_FLAG_BLOCK_SELF_IMPLICIT_HYDRATION = 0x0000_0008,
  CF_CONNECT_FLAG_NONE = 0x0000_0000,
  CF_CONNECT_FLAG_REQUIRE_FULL_FILE_PATH = 0x0000_0004,
  CF_CONNECT_FLAG_REQUIRE_PROCESS_INFO = 0x0000_0002,
}

export enum CF_CONVERT_FLAGS {
  CF_CONVERT_FLAG_ALWAYS_FULL = 0x0000_0008,
  CF_CONVERT_FLAG_DEHYDRATE = 0x0000_0002,
  CF_CONVERT_FLAG_ENABLE_ON_DEMAND_POPULATION = 0x0000_0004,
  CF_CONVERT_FLAG_FORCE_CONVERT_TO_CLOUD_FILE = 0x0000_0010,
  CF_CONVERT_FLAG_MARK_IN_SYNC = 0x0000_0001,
  CF_CONVERT_FLAG_NONE = 0x0000_0000,
}

export enum CF_CREATE_FLAGS {
  CF_CREATE_FLAG_NONE = 0x0000_0000,
  CF_CREATE_FLAG_STOP_ON_ERROR = 0x0000_0001,
}

export enum CF_DEHYDRATE_FLAGS {
  CF_DEHYDRATE_FLAG_BACKGROUND = 0x0000_0001,
  CF_DEHYDRATE_FLAG_NONE = 0x0000_0000,
}

export enum CF_HARDLINK_POLICY {
  CF_HARDLINK_POLICY_ALLOWED = 0x0000_0001,
  CF_HARDLINK_POLICY_NONE = 0x0000_0000,
}

export enum CF_HYDRATE_FLAGS {
  CF_HYDRATE_FLAG_NONE = 0x0000_0000,
}

export enum CF_HYDRATION_POLICY_MODIFIER {
  CF_HYDRATION_POLICY_MODIFIER_ALLOW_FULL_RESTART_HYDRATION = 0x0000_0008,
  CF_HYDRATION_POLICY_MODIFIER_AUTO_DEHYDRATION_ALLOWED = 0x0000_0004,
  CF_HYDRATION_POLICY_MODIFIER_NONE = 0x0000_0000,
  CF_HYDRATION_POLICY_MODIFIER_STREAMING_ALLOWED = 0x0000_0002,
  CF_HYDRATION_POLICY_MODIFIER_VALIDATION_REQUIRED = 0x0000_0001,
}

export enum CF_HYDRATION_POLICY_PRIMARY {
  CF_HYDRATION_POLICY_ALWAYS_FULL = 3,
  CF_HYDRATION_POLICY_FULL = 2,
  CF_HYDRATION_POLICY_PARTIAL = 0,
  CF_HYDRATION_POLICY_PROGRESSIVE = 1,
}

export enum CF_INSYNC_POLICY {
  CF_INSYNC_POLICY_NONE = 0x0000_0000,
  CF_INSYNC_POLICY_PRESERVE_INSYNC_FOR_SYNC_ENGINE = 0x8000_0000,
  CF_INSYNC_POLICY_TRACK_ALL = 0x00ff_ffff,
  CF_INSYNC_POLICY_TRACK_DIRECTORY_ALL = 0x00aa_aaf0,
  CF_INSYNC_POLICY_TRACK_DIRECTORY_CREATION_TIME = 0x0000_0010,
  CF_INSYNC_POLICY_TRACK_DIRECTORY_HIDDEN_ATTRIBUTE = 0x0000_0040,
  CF_INSYNC_POLICY_TRACK_DIRECTORY_LAST_WRITE_TIME = 0x0000_0200,
  CF_INSYNC_POLICY_TRACK_DIRECTORY_READONLY_ATTRIBUTE = 0x0000_0020,
  CF_INSYNC_POLICY_TRACK_DIRECTORY_SYSTEM_ATTRIBUTE = 0x0000_0080,
  CF_INSYNC_POLICY_TRACK_FILE_ALL = 0x0055_550f,
  CF_INSYNC_POLICY_TRACK_FILE_CREATION_TIME = 0x0000_0001,
  CF_INSYNC_POLICY_TRACK_FILE_HIDDEN_ATTRIBUTE = 0x0000_0004,
  CF_INSYNC_POLICY_TRACK_FILE_LAST_WRITE_TIME = 0x0000_0100,
  CF_INSYNC_POLICY_TRACK_FILE_READONLY_ATTRIBUTE = 0x0000_0002,
  CF_INSYNC_POLICY_TRACK_FILE_SYSTEM_ATTRIBUTE = 0x0000_0008,
}

export enum CF_IN_SYNC_STATE {
  CF_IN_SYNC_STATE_IN_SYNC = 1,
  CF_IN_SYNC_STATE_NOT_IN_SYNC = 0,
}

export enum CF_OPEN_FILE_FLAGS {
  CF_OPEN_FILE_FLAG_DELETE_ACCESS = 0x0000_0004,
  CF_OPEN_FILE_FLAG_EXCLUSIVE = 0x0000_0001,
  CF_OPEN_FILE_FLAG_FOREGROUND = 0x0000_0008,
  CF_OPEN_FILE_FLAG_NONE = 0x0000_0000,
  CF_OPEN_FILE_FLAG_WRITE_ACCESS = 0x0000_0002,
}

export enum CF_OPERATION_ACK_DATA_FLAGS {
  CF_OPERATION_ACK_DATA_FLAG_NONE = 0x0000_0000,
}

export enum CF_OPERATION_ACK_DEHYDRATE_FLAGS {
  CF_OPERATION_ACK_DEHYDRATE_FLAG_NONE = 0x0000_0000,
}

export enum CF_OPERATION_ACK_DELETE_FLAGS {
  CF_OPERATION_ACK_DELETE_FLAG_NONE = 0x0000_0000,
}

export enum CF_OPERATION_ACK_RENAME_FLAGS {
  CF_OPERATION_ACK_RENAME_FLAG_NONE = 0x0000_0000,
}

export enum CF_OPERATION_RESTART_HYDRATION_FLAGS {
  CF_OPERATION_RESTART_HYDRATION_FLAG_MARK_IN_SYNC = 0x0000_0001,
  CF_OPERATION_RESTART_HYDRATION_FLAG_NONE = 0x0000_0000,
}

export enum CF_OPERATION_RETRIEVE_DATA_FLAGS {
  CF_OPERATION_RETRIEVE_DATA_FLAG_NONE = 0x0000_0000,
}

export enum CF_OPERATION_TRANSFER_DATA_FLAGS {
  CF_OPERATION_TRANSFER_DATA_FLAG_NONE = 0x0000_0000,
}

export enum CF_OPERATION_TRANSFER_PLACEHOLDERS_FLAGS {
  CF_OPERATION_TRANSFER_PLACEHOLDERS_FLAG_DISABLE_ON_DEMAND_POPULATION = 0x0000_0002,
  CF_OPERATION_TRANSFER_PLACEHOLDERS_FLAG_NONE = 0x0000_0000,
  CF_OPERATION_TRANSFER_PLACEHOLDERS_FLAG_STOP_ON_ERROR = 0x0000_0001,
}

export enum CF_OPERATION_TYPE {
  CF_OPERATION_TYPE_ACK_DATA = 2,
  CF_OPERATION_TYPE_ACK_DEHYDRATE = 5,
  CF_OPERATION_TYPE_ACK_DELETE = 6,
  CF_OPERATION_TYPE_ACK_RENAME = 7,
  CF_OPERATION_TYPE_RESTART_HYDRATION = 3,
  CF_OPERATION_TYPE_RETRIEVE_DATA = 1,
  CF_OPERATION_TYPE_TRANSFER_DATA = 0,
  CF_OPERATION_TYPE_TRANSFER_PLACEHOLDERS = 4,
}

export enum CF_PIN_STATE {
  CF_PIN_STATE_EXCLUDED = 3,
  CF_PIN_STATE_INHERIT = 4,
  CF_PIN_STATE_PINNED = 1,
  CF_PIN_STATE_UNPINNED = 2,
  CF_PIN_STATE_UNSPECIFIED = 0,
}

export enum CF_PLACEHOLDER_CREATE_FLAGS {
  CF_PLACEHOLDER_CREATE_FLAG_ALWAYS_FULL = 0x0000_0008,
  CF_PLACEHOLDER_CREATE_FLAG_DISABLE_ON_DEMAND_POPULATION = 0x0000_0001,
  CF_PLACEHOLDER_CREATE_FLAG_MARK_IN_SYNC = 0x0000_0002,
  CF_PLACEHOLDER_CREATE_FLAG_NONE = 0x0000_0000,
  CF_PLACEHOLDER_CREATE_FLAG_SUPERSEDE = 0x0000_0004,
}

export enum CF_PLACEHOLDER_INFO_CLASS {
  CF_PLACEHOLDER_INFO_BASIC = 0,
  CF_PLACEHOLDER_INFO_STANDARD = 1,
}

export enum CF_PLACEHOLDER_MANAGEMENT_POLICY {
  CF_PLACEHOLDER_MANAGEMENT_POLICY_CONVERT_TO_UNRESTRICTED = 0x0000_0002,
  CF_PLACEHOLDER_MANAGEMENT_POLICY_CREATE_UNRESTRICTED = 0x0000_0001,
  CF_PLACEHOLDER_MANAGEMENT_POLICY_DEFAULT = 0x0000_0000,
  CF_PLACEHOLDER_MANAGEMENT_POLICY_UPDATE_UNRESTRICTED = 0x0000_0004,
}

export enum CF_PLACEHOLDER_RANGE_INFO_CLASS {
  CF_PLACEHOLDER_RANGE_INFO_MODIFIED = 3,
  CF_PLACEHOLDER_RANGE_INFO_ONDISK = 1,
  CF_PLACEHOLDER_RANGE_INFO_VALIDATED = 2,
}

export enum CF_PLACEHOLDER_STATE {
  CF_PLACEHOLDER_STATE_ESSENTIAL_PROP_PRESENT = 0x0000_0004,
  CF_PLACEHOLDER_STATE_INVALID = 0xffff_ffff,
  CF_PLACEHOLDER_STATE_IN_SYNC = 0x0000_0008,
  CF_PLACEHOLDER_STATE_NO_STATES = 0x0000_0000,
  CF_PLACEHOLDER_STATE_PARTIAL = 0x0000_0010,
  CF_PLACEHOLDER_STATE_PARTIALLY_ON_DISK = 0x0000_0020,
  CF_PLACEHOLDER_STATE_PLACEHOLDER = 0x0000_0001,
  CF_PLACEHOLDER_STATE_SYNC_ROOT = 0x0000_0002,
}

export enum CF_POPULATION_POLICY_MODIFIER {
  CF_POPULATION_POLICY_MODIFIER_NONE = 0x0000_0000,
}

export enum CF_POPULATION_POLICY_PRIMARY {
  CF_POPULATION_POLICY_ALWAYS_FULL = 3,
  CF_POPULATION_POLICY_FULL = 2,
  CF_POPULATION_POLICY_PARTIAL = 0,
}

export enum CF_REGISTER_FLAGS {
  CF_REGISTER_FLAG_DISABLE_ON_DEMAND_POPULATION_ON_ROOT = 0x0000_0002,
  CF_REGISTER_FLAG_MARK_IN_SYNC_ON_ROOT = 0x0000_0004,
  CF_REGISTER_FLAG_NONE = 0x0000_0000,
  CF_REGISTER_FLAG_UPDATE = 0x0000_0001,
}

export enum CF_REVERT_FLAGS {
  CF_REVERT_FLAG_NONE = 0x0000_0000,
}

export enum CF_SET_IN_SYNC_FLAGS {
  CF_SET_IN_SYNC_FLAG_NONE = 0x0000_0000,
}

export enum CF_SET_PIN_FLAGS {
  CF_SET_PIN_FLAG_NONE = 0x0000_0000,
  CF_SET_PIN_FLAG_RECURSE = 0x0000_0001,
  CF_SET_PIN_FLAG_RECURSE_ONLY = 0x0000_0002,
  CF_SET_PIN_FLAG_RECURSE_STOP_ON_ERROR = 0x0000_0004,
}

export enum CF_SYNC_PROVIDER_STATUS {
  CF_PROVIDER_STATUS_CLEAR_FLAGS = 0x8000_0000,
  CF_PROVIDER_STATUS_CONNECTIVITY_LOST = 0x0000_0040,
  CF_PROVIDER_STATUS_DISCONNECTED = 0x0000_0000,
  CF_PROVIDER_STATUS_ERROR = 0xc000_0002,
  CF_PROVIDER_STATUS_IDLE = 0x0000_0001,
  CF_PROVIDER_STATUS_POPULATE_CONTENT = 0x0000_0008,
  CF_PROVIDER_STATUS_POPULATE_METADATA = 0x0000_0004,
  CF_PROVIDER_STATUS_POPULATE_NAMESPACE = 0x0000_0002,
  CF_PROVIDER_STATUS_SYNC_FULL = 0x0000_0020,
  CF_PROVIDER_STATUS_SYNC_INCREMENTAL = 0x0000_0010,
  CF_PROVIDER_STATUS_TERMINATED = 0xc000_0001,
}

export enum CF_SYNC_ROOT_INFO_CLASS {
  CF_SYNC_ROOT_INFO_BASIC = 0,
  CF_SYNC_ROOT_INFO_PROVIDER = 2,
  CF_SYNC_ROOT_INFO_STANDARD = 1,
}

export enum CF_UPDATE_FLAGS {
  CF_UPDATE_FLAG_ALLOW_PARTIAL = 0x0000_0400,
  CF_UPDATE_FLAG_ALWAYS_FULL = 0x0000_0200,
  CF_UPDATE_FLAG_CLEAR_IN_SYNC = 0x0000_0040,
  CF_UPDATE_FLAG_DEHYDRATE = 0x0000_0004,
  CF_UPDATE_FLAG_DISABLE_ON_DEMAND_POPULATION = 0x0000_0010,
  CF_UPDATE_FLAG_ENABLE_ON_DEMAND_POPULATION = 0x0000_0008,
  CF_UPDATE_FLAG_MARK_IN_SYNC = 0x0000_0002,
  CF_UPDATE_FLAG_NONE = 0x0000_0000,
  CF_UPDATE_FLAG_PASSTHROUGH_FS_METADATA = 0x0000_0100,
  CF_UPDATE_FLAG_REMOVE_FILE_IDENTITY = 0x0000_0020,
  CF_UPDATE_FLAG_REMOVE_PROPERTY = 0x0000_0080,
  CF_UPDATE_FLAG_VERIFY_IN_SYNC = 0x0000_0001,
}

export type CF_CONNECTION_KEY = bigint;
export type CF_REQUEST_KEY = bigint;
export type CF_TRANSFER_KEY = bigint;
export type FILE_INFO_BY_HANDLE_CLASS = number;
export type LARGE_INTEGER = bigint;
export type LPOVERLAPPED = Pointer;
export type PCF_CALLBACK_REGISTRATION = Pointer;
export type PCF_CONNECTION_KEY = Pointer;
export type PCF_FILE_RANGE = Pointer;
export type PCF_FS_METADATA = Pointer;
export type PCF_OPERATION_INFO = Pointer;
export type PCF_OPERATION_PARAMETERS = Pointer;
export type PCF_PLACEHOLDER_CREATE_INFO = Pointer;
export type PCF_PLATFORM_INFO = Pointer;
export type PCF_SYNC_POLICIES = Pointer;
export type PCF_SYNC_PROVIDER_STATUS = Pointer;
export type PCF_SYNC_REGISTRATION = Pointer;
export type PCF_SYNC_STATUS = Pointer;
export type PCF_TRANSFER_KEY = Pointer;
export type PCORRELATION_VECTOR = Pointer;
export type PUSN = Pointer;
export type PWIN32_FIND_DATAW = Pointer;
