import type { Pointer } from 'bun:ffi';
export type { BOOL, DWORD, HRESULT, HWND, INT, LPCVOID, LPBOOL, LPDWORD, LPARAM, LRESULT, NULL, Nullable, Optional, PVOID, UINT, WPARAM } from '@bun-win32/core';

export enum BlurBehindFlags {
  DWM_BB_BLURREGION = 0x0000_0002,
  DWM_BB_ENABLE = 0x0000_0001,
  DWM_BB_TRANSITIONONMAXIMIZED = 0x0000_0004,
}

export enum CloakedReason {
  DWM_CLOAKED_APP = 0x0000_0001,
  DWM_CLOAKED_INHERITED = 0x0000_0004,
  DWM_CLOAKED_SHELL = 0x0000_0002,
}

export enum EnableCompositionAction {
  DWM_EC_DISABLECOMPOSITION = 0,
  DWM_EC_ENABLECOMPOSITION = 1,
}

export enum Flip3DWindowPolicy {
  DWMFLIP3D_DEFAULT = 0,
  DWMFLIP3D_EXCLUDEABOVE = 2,
  DWMFLIP3D_EXCLUDEBELOW = 1,
  DWMFLIP3D_LAST = 3,
}

export enum GestureType {
  GT_PEN_DOUBLETAP = 1,
  GT_PEN_PRESSANDHOLD = 3,
  GT_PEN_PRESSANDHOLDABORT = 4,
  GT_PEN_RIGHTTAP = 2,
  GT_PEN_TAP = 0,
  GT_TOUCH_DOUBLETAP = 6,
  GT_TOUCH_PRESSANDHOLD = 8,
  GT_TOUCH_PRESSANDHOLDABORT = 9,
  GT_TOUCH_PRESSANDTAP = 10,
  GT_TOUCH_RIGHTTAP = 7,
  GT_TOUCH_TAP = 5,
}

export enum NCRenderingPolicy {
  DWMNCRP_DISABLED = 1,
  DWMNCRP_ENABLED = 2,
  DWMNCRP_LAST = 3,
  DWMNCRP_USEWINDOWSTYLE = 0,
}

export enum SetIconicThumbnailFlags {
  DWM_SIT_DISPLAYFRAME = 0x0000_0001,
}

export enum ShowContact {
  DWMSC_ALL = 0xffff_ffff,
  DWMSC_DOWN = 0x0000_0001,
  DWMSC_DRAG = 0x0000_0004,
  DWMSC_HOLD = 0x0000_0008,
  DWMSC_NONE = 0x0000_0000,
  DWMSC_PENBARREL = 0x0000_0010,
  DWMSC_UP = 0x0000_0002,
}

export enum SystemBackdropType {
  DWMSBT_AUTO = 0,
  DWMSBT_MAINWINDOW = 2,
  DWMSBT_NONE = 1,
  DWMSBT_TABBEDWINDOW = 4,
  DWMSBT_TRANSIENTWINDOW = 3,
}

export enum TabWindowRequirements {
  DWMTWR_GROUP_POLICY_ENABLED = 0x0000_0040,
  DWMTWR_IMPLEMENTED_VIA_DWM_SETTAB_PROPERTIES = 0x0000_0001,
  DWMTWR_NONE = 0x0000_0000,
  DWMTWR_TABBING_ENABLED = 0x0000_0010,
  DWMTWR_USER_POLICY_ENABLED = 0x0000_0020,
  DWMTWR_WINDOW_RELATIONSHIP_OWNER_ACTIVE = 0x0000_0004,
  DWMTWR_WINDOW_RELATIONSHIP_OWNER_HAS_SETCLIENTAREAANIMATION = 0x0000_0002,
  DWMTWR_WINDOW_RELATIONSHIP_OWNER_UNOWNED = 0x0000_0008,
}

export enum ThumbnailPropertiesFlags {
  DWM_TNP_OPACITY = 0x0000_0004,
  DWM_TNP_RECTDESTINATION = 0x0000_0001,
  DWM_TNP_RECTSOURCE = 0x0000_0002,
  DWM_TNP_SOURCECLIENTAREAONLY = 0x0000_0010,
  DWM_TNP_VISIBLE = 0x0000_0008,
}

export enum TransitionOwnedWindowTarget {
  DWMTRANSITION_OWNEDWINDOW_NULL = -1,
  DWMTRANSITION_OWNEDWINDOW_REPOSITION = 0x0000_0001,
}

export enum WindowAttribute {
  DWMWA_ALLOW_NCPAINT = 4,
  DWMWA_BORDER_COLOR = 34,
  DWMWA_CAPTION_BUTTON_BOUNDS = 5,
  DWMWA_CAPTION_COLOR = 35,
  DWMWA_CLOAK = 13,
  DWMWA_CLOAKED = 14,
  DWMWA_DISALLOW_PEEK = 11,
  DWMWA_EXCLUDED_FROM_PEEK = 12,
  DWMWA_EXTENDED_FRAME_BOUNDS = 9,
  DWMWA_FLIP3D_POLICY = 8,
  DWMWA_FORCE_ICONIC_REPRESENTATION = 7,
  DWMWA_FREEZE_REPRESENTATION = 15,
  DWMWA_HAS_ICONIC_BITMAP = 10,
  DWMWA_LAST = 39,
  DWMWA_NCRENDERING_ENABLED = 1,
  DWMWA_NCRENDERING_POLICY = 2,
  DWMWA_NONCLIENT_RTL_LAYOUT = 6,
  DWMWA_PASSIVE_UPDATE_MODE = 16,
  DWMWA_SYSTEMBACKDROP_TYPE = 38,
  DWMWA_TEXT_COLOR = 36,
  DWMWA_TRANSITIONS_FORCEDISABLED = 3,
  DWMWA_USE_HOSTBACKDROPBRUSH = 17,
  DWMWA_USE_IMMERSIVE_DARK_MODE = 20,
  DWMWA_VISIBLE_FRAME_BORDER_THICKNESS = 37,
  DWMWA_WINDOW_CORNER_PREFERENCE = 33,
}

export enum WindowCornerPreference {
  DWMWCP_DEFAULT = 0,
  DWMWCP_DONOTROUND = 1,
  DWMWCP_ROUND = 2,
  DWMWCP_ROUNDSMALL = 3,
}

export type DWM_SHOWCONTACT = number;
export type DWMTRANSITION_OWNEDWINDOW_TARGET = number;
export type GESTURE_TYPE = number;
export type HBITMAP = bigint;
export type HTHUMBNAIL = bigint;
export type PACKED_POINT = bigint;
export type PDWM_BLURBEHIND = Pointer;
export type PDWM_PRESENT_PARAMETERS = Pointer;
export type PDWM_TAB_WINDOW_REQUIREMENTS = Pointer;
export type PDWM_THUMBNAIL_PROPERTIES = Pointer;
export type PDWM_TIMING_INFO = Pointer;
export type PHTHUMBNAIL = Pointer;
export type PLRESULT = Pointer;
export type PMARGINS = Pointer;
export type PPOINT = Pointer;
export type PSIZE = Pointer;

const _packBuf = Buffer.alloc(8);

/** Pack two `LONG` values into a `PACKED_POINT` for Win32 functions that take `POINT` by value. */
export function packPOINT(x: number, y: number): PACKED_POINT {
  _packBuf.writeInt32LE(x, 0);
  _packBuf.writeInt32LE(y, 4);
  return _packBuf.readBigUInt64LE(0);
}
