import type { Pointer } from 'bun:ffi';

export type { HRESULT, HWND, LPCWSTR, LPVOID, LPWSTR, NULL, Nullable, Optional } from '@bun-win32/core';

export type GUID = Pointer;
export type IMFASFContentInfo = Pointer;
export type IMFASFProfile = Pointer;
export type IMFActivate = Pointer;
export type IMFAttributes = Pointer;
export type IMFByteStream = Pointer;
export type IMFMediaSink = Pointer;
export type IMFMediaType = Pointer;
export type IMFPresentationDescriptor = Pointer;
export type IPropertyStore = Pointer;
export type IUnknown = Pointer;
export type LPLPVOID = Pointer;
export type PBYTE = Pointer;
export type PIMFASFContentInfo = Pointer;
export type PIMFASFIndexer = Pointer;
export type PIMFASFMultiplexer = Pointer;
export type PIMFASFProfile = Pointer;
export type PIMFASFSplitter = Pointer;
export type PIMFASFStreamSelector = Pointer;
export type PIMFActivate = Pointer;
export type PIMFByteStream = Pointer;
export type PIMFMediaSink = Pointer;
export type PIMFNetCredentialCache = Pointer;
export type PIMFNetProxyLocator = Pointer;
export type PIMFPresentationDescriptor = Pointer;
export type PIMFProtectedEnvironmentAccess = Pointer;
export type PIMFRemoteDesktopPlugin = Pointer;
export type PIMFSignedLibrary = Pointer;
export type PIMFSourceResolver = Pointer;
export type PIMFSystemId = Pointer;
export type PLPWSTR = Pointer;
export type PPROPVARIANT = Pointer;
export type QWORD = bigint;
export type REFCLSID = Pointer;
export type REFIID = Pointer;
export type UINT32 = number;
