import type { Pointer } from 'bun:ffi';
export type { BOOL, BYTE, DWORD, HANDLE, HMODULE, LPCSTR, LPCWSTR, LPDWORD, LONG, LPSTR, LPVOID, LPWSTR, NULL, Nullable, Optional, PBYTE, PDWORD, PVOID, ULONG } from '@bun-win32/core';

export enum CertCloseStoreFlag {
  CERT_CLOSE_STORE_CHECK_FLAG = 0x0000_0002,
  CERT_CLOSE_STORE_FORCE_FLAG = 0x0000_0001,
}

export enum CertEncodingType {
  PKCS_7_ASN_ENCODING = 0x0001_0000,
  X509_ASN_ENCODING = 0x0000_0001,
}

export enum CertNameType {
  CERT_NAME_ATTR_TYPE = 0x0000_0003,
  CERT_NAME_DNS_TYPE = 0x0000_0006,
  CERT_NAME_EMAIL_TYPE = 0x0000_0001,
  CERT_NAME_FRIENDLY_DISPLAY_TYPE = 0x0000_0005,
  CERT_NAME_RDN_TYPE = 0x0000_0002,
  CERT_NAME_SIMPLE_DISPLAY_TYPE = 0x0000_0004,
  CERT_NAME_URL_TYPE = 0x0000_0007,
  CERT_NAME_UPN_TYPE = 0x0000_0008,
}

export enum CertStoreAddDisposition {
  CERT_STORE_ADD_ALWAYS = 0x0000_0004,
  CERT_STORE_ADD_NEW = 0x0000_0001,
  CERT_STORE_ADD_NEWER = 0x0000_0006,
  CERT_STORE_ADD_NEWER_INHERIT_PROPERTIES = 0x0000_0007,
  CERT_STORE_ADD_REPLACE_EXISTING = 0x0000_0003,
  CERT_STORE_ADD_REPLACE_EXISTING_INHERIT_PROPERTIES = 0x0000_0005,
  CERT_STORE_ADD_USE_EXISTING = 0x0000_0002,
}

export enum CertStoreSaveAs {
  CERT_STORE_SAVE_AS_PKCS7 = 0x0000_0002,
  CERT_STORE_SAVE_AS_STORE = 0x0000_0001,
}

export enum CertStoreSaveTo {
  CERT_STORE_SAVE_TO_FILE = 0x0000_0003,
  CERT_STORE_SAVE_TO_FILENAME_A = 0x0000_0004,
  CERT_STORE_SAVE_TO_FILENAME_W = 0x0000_0005,
  CERT_STORE_SAVE_TO_MEMORY = 0x0000_0002,
}

export enum CryptBinaryToStringFlags {
  CRYPT_STRING_BASE64 = 0x0000_0001,
  CRYPT_STRING_BASE64HEADER = 0x0000_0000,
  CRYPT_STRING_BASE64REQUESTHEADER = 0x0000_0003,
  CRYPT_STRING_BASE64X509CRLHEADER = 0x0000_0009,
  CRYPT_STRING_BINARY = 0x0000_0002,
  CRYPT_STRING_HEX = 0x0000_0004,
  CRYPT_STRING_HEXADDR = 0x0000_000a,
  CRYPT_STRING_HEXASCII = 0x0000_0005,
  CRYPT_STRING_HEXASCIIADDR = 0x0000_000b,
  CRYPT_STRING_HEXRAW = 0x0000_000c,
  CRYPT_STRING_NOCR = 0x8000_0000,
  CRYPT_STRING_NOCRLF = 0x4000_0000,
  CRYPT_STRING_STRICT = 0x2000_0000,
}

export enum CryptMsgType {
  CMSG_DATA = 1,
  CMSG_ENVELOPED = 3,
  CMSG_HASHED = 5,
  CMSG_SIGNED = 2,
  CMSG_SIGNED_AND_ENVELOPED = 4,
}

export enum CryptProtectFlags {
  CRYPTPROTECT_AUDIT = 0x0000_0010,
  CRYPTPROTECT_LOCAL_MACHINE = 0x0000_0004,
  CRYPTPROTECT_NO_RECOVERY = 0x0000_0020,
  CRYPTPROTECT_UI_FORBIDDEN = 0x0000_0001,
  CRYPTPROTECT_VERIFY_PROTECTION = 0x0000_0040,
}

export enum CryptQueryContentTypeFlags {
  CERT_QUERY_CONTENT_FLAG_ALL = 0x0000_3ffe,
  CERT_QUERY_CONTENT_FLAG_CERT = 0x0000_0002,
  CERT_QUERY_CONTENT_FLAG_CRL = 0x0000_0004,
  CERT_QUERY_CONTENT_FLAG_CTL = 0x0000_0008,
  CERT_QUERY_CONTENT_FLAG_PFX = 0x0000_1000,
  CERT_QUERY_CONTENT_FLAG_PKCS7_SIGNED = 0x0000_0100,
  CERT_QUERY_CONTENT_FLAG_PKCS7_UNSIGNED = 0x0000_0200,
  CERT_QUERY_CONTENT_FLAG_SERIALIZED_STORE = 0x0000_0010,
}

export enum CryptQueryFormatTypeFlags {
  CERT_QUERY_FORMAT_FLAG_ALL = 0x0000_000e,
  CERT_QUERY_FORMAT_FLAG_ASN_ASCII_HEX_ENCODED = 0x0000_0008,
  CERT_QUERY_FORMAT_FLAG_BASE64_ENCODED = 0x0000_0004,
  CERT_QUERY_FORMAT_FLAG_BINARY = 0x0000_0002,
}

export enum PFXImportFlags {
  CRYPT_EXPORTABLE = 0x0000_0001,
  CRYPT_MACHINE_KEYSET = 0x0000_0020,
  CRYPT_USER_KEYSET = 0x0000_1000,
  CRYPT_USER_PROTECTED = 0x0000_0002,
  PKCS12_ALLOW_OVERWRITE_KEY = 0x0000_4000,
  PKCS12_ALWAYS_CNG_KSP = 0x0000_0200,
  PKCS12_INCLUDE_EXTENDED_PROPERTIES = 0x0000_0010,
  PKCS12_NO_PERSIST_KEY = 0x0000_8000,
  PKCS12_PREFER_CNG_KSP = 0x0000_0100,
}

export type ALG_ID = number;
export type BCRYPT_KEY_HANDLE = bigint;
export type HCERT_SERVER_OCSP_RESPONSE = bigint;
export type HCERTCHAINENGINE = bigint;
export type HCERTSTORE = bigint;
export type HCRYPTASYNC = bigint;
export type HCRYPTDEFAULTCONTEXT = bigint;
export type HCRYPTMSG = bigint;
export type HCRYPTOIDFUNCADDR = bigint;
export type HCRYPTOIDFUNCSET = bigint;
export type HCRYPTPROV = bigint;
export type HCRYPTPROV_OR_NCRYPT_KEY_HANDLE = bigint;
export type LPFILETIME = Pointer;
export type PCCERT_CHAIN_CONTEXT = Pointer;
export type PCCERT_CONTEXT = Pointer;
export type PCCERT_SELECT_CRITERIA = Pointer;
export type PCCERT_SERVER_OCSP_RESPONSE_CONTEXT = Pointer;
export type PCCRL_CONTEXT = Pointer;
export type PCCTL_CONTEXT = Pointer;
export type PCCRYPT_OID_INFO = Pointer;
export type PCERT_CHAIN_ENGINE_CONFIG = Pointer;
export type PCERT_CHAIN_PARA = Pointer;
export type PCERT_CHAIN_POLICY_PARA = Pointer;
export type PCERT_CHAIN_POLICY_STATUS = Pointer;
export type PCERT_CREATE_CONTEXT_PARA = Pointer;
export type PCERT_ENHKEY_USAGE = Pointer;
export type PCERT_EXTENSION = Pointer;
export type PCERT_EXTENSIONS = Pointer;
export type PCERT_INFO = Pointer;
export type PCERT_NAME_BLOB = Pointer;
export type PCERT_NAME_INFO = Pointer;
export type PCERT_PUBLIC_KEY_INFO = Pointer;
export type PCERT_RDN = Pointer;
export type PCERT_RDN_ATTR = Pointer;
export type PCERT_RDN_VALUE_BLOB = Pointer;
export type PCERT_REVOCATION_PARA = Pointer;
export type PCERT_REVOCATION_STATUS = Pointer;
export type PCERT_SERVER_OCSP_RESPONSE_OPEN_PARA = Pointer;
export type PCERT_STRONG_SIGN_PARA = Pointer;
export type PCMSG_SIGNED_ENCODE_INFO = Pointer;
export type PCMSG_SIGNER_ENCODE_INFO = Pointer;
export type PCMSG_STREAM_INFO = Pointer;
export type PCRL_INFO = Pointer;
export type PCRYPT_ALGORITHM_IDENTIFIER = Pointer;
export type PCRYPT_ATTRIBUTE = Pointer;
export type PCRYPT_DATA_BLOB = Pointer;
export type PCRYPT_DECODE_PARA = Pointer;
export type PCRYPT_DECRYPT_MESSAGE_PARA = Pointer;
export type PCRYPT_DER_BLOB = Pointer;
export type PCRYPT_ENCODE_PARA = Pointer;
export type PCRYPT_ENCRYPT_MESSAGE_PARA = Pointer;
export type PCRYPT_HASH_MESSAGE_PARA = Pointer;
export type PCRYPT_INTEGER_BLOB = Pointer;
export type PCRYPT_KEY_PROV_INFO = Pointer;
export type PCRYPT_KEY_SIGN_MESSAGE_PARA = Pointer;
export type PCRYPT_KEY_VERIFY_MESSAGE_PARA = Pointer;
export type PCRYPT_OID_FUNC_ENTRY = Pointer;
export type PCRYPT_SIGN_MESSAGE_PARA = Pointer;
export type PCRYPT_TIMESTAMP_CONTEXT = Pointer;
export type PCRYPT_TIMESTAMP_PARA = Pointer;
export type PCRYPT_VERIFY_MESSAGE_PARA = Pointer;
export type PCRYPTPROTECT_PROMPTSTRUCT = Pointer;
export type PCTL_ENTRY = Pointer;
export type PCTL_INFO = Pointer;
export type PCTL_USAGE = Pointer;
export type PCTL_VERIFY_USAGE_PARA = Pointer;
export type PCTL_VERIFY_USAGE_STATUS = Pointer;
export type PDATA_BLOB = Pointer;
export type PFN_CERT_ENUM_PHYSICAL_STORE = Pointer;
export type PFN_CERT_ENUM_SYSTEM_STORE = Pointer;
export type PFN_CERT_ENUM_SYSTEM_STORE_LOCATION = Pointer;
export type PFN_CRYPT_ENUM_KEYID_PROP = Pointer;
export type PFN_CRYPT_ENUM_OID_FUNC = Pointer;
export type PFN_CRYPT_ENUM_OID_INFO = Pointer;
export type PSIP_ADD_NEWPROVIDER = Pointer;
export type PSIP_CAP_SET_V3 = Pointer;
export type PSIP_DISPATCH_INFO = Pointer;
export type PSIP_INDIRECT_DATA = Pointer;
export type PSIP_SUBJECTINFO = Pointer;
export type PSYSTEMTIME = Pointer;
