import type { Pointer } from 'bun:ffi';

export type { DWORD, HANDLE, LPCVOID, LPCWSTR, LPWSTR, NULL, Nullable, Optional, PHANDLE, PULONG, PVOID, ULONG } from '@bun-win32/core';

export const CREATE_VIRTUAL_DISK_PARAMETERS_DEFAULT_BLOCK_SIZE = 0;
export const CREATE_VIRTUAL_DISK_PARAMETERS_DEFAULT_SECTOR_SIZE = 0;
export const MERGE_VIRTUAL_DISK_DEFAULT_MERGE_DEPTH = 1;
export const OPEN_VIRTUAL_DISK_RW_DEPTH_DEFAULT = 1;
export const VIRTUAL_DISK_MAXIMUM_CHANGE_TRACKING_ID_LENGTH = 256;
export const VIRTUAL_STORAGE_TYPE_DEVICE_ISO = 1;
export const VIRTUAL_STORAGE_TYPE_DEVICE_UNKNOWN = 0;
export const VIRTUAL_STORAGE_TYPE_DEVICE_VHD = 2;
export const VIRTUAL_STORAGE_TYPE_DEVICE_VHDSET = 4;
export const VIRTUAL_STORAGE_TYPE_DEVICE_VHDX = 3;

export enum APPLY_SNAPSHOT_VHDSET_FLAG {
  APPLY_SNAPSHOT_VHDSET_FLAG_NONE = 0x0000_0000,
  APPLY_SNAPSHOT_VHDSET_FLAG_WRITEABLE = 0x0000_0001,
}

export enum APPLY_SNAPSHOT_VHDSET_VERSION {
  APPLY_SNAPSHOT_VHDSET_VERSION_UNSPECIFIED = 0,
  APPLY_SNAPSHOT_VHDSET_VERSION_1 = 1,
}

export enum ATTACH_VIRTUAL_DISK_FLAG {
  ATTACH_VIRTUAL_DISK_FLAG_NONE = 0x0000_0000,
  ATTACH_VIRTUAL_DISK_FLAG_READ_ONLY = 0x0000_0001,
  ATTACH_VIRTUAL_DISK_FLAG_NO_DRIVE_LETTER = 0x0000_0002,
  ATTACH_VIRTUAL_DISK_FLAG_PERMANENT_LIFETIME = 0x0000_0004,
  ATTACH_VIRTUAL_DISK_FLAG_NO_LOCAL_HOST = 0x0000_0008,
  ATTACH_VIRTUAL_DISK_FLAG_NO_SECURITY_DESCRIPTOR = 0x0000_0010,
  ATTACH_VIRTUAL_DISK_FLAG_BYPASS_DEFAULT_ENCRYPTION_POLICY = 0x0000_0020,
  ATTACH_VIRTUAL_DISK_FLAG_NON_PNP = 0x0000_0040,
  ATTACH_VIRTUAL_DISK_FLAG_RESTRICTED_RANGE = 0x0000_0080,
  ATTACH_VIRTUAL_DISK_FLAG_SINGLE_PARTITION = 0x0000_0100,
  ATTACH_VIRTUAL_DISK_FLAG_REGISTER_VOLUME = 0x0000_0200,
}

export enum ATTACH_VIRTUAL_DISK_VERSION {
  ATTACH_VIRTUAL_DISK_VERSION_UNSPECIFIED = 0,
  ATTACH_VIRTUAL_DISK_VERSION_1 = 1,
  ATTACH_VIRTUAL_DISK_VERSION_2 = 2,
}

export enum COMPACT_VIRTUAL_DISK_FLAG {
  COMPACT_VIRTUAL_DISK_FLAG_NONE = 0x0000_0000,
  COMPACT_VIRTUAL_DISK_FLAG_NO_ZERO_SCAN = 0x0000_0001,
  COMPACT_VIRTUAL_DISK_FLAG_NO_BLOCK_MOVES = 0x0000_0002,
}

export enum COMPACT_VIRTUAL_DISK_VERSION {
  COMPACT_VIRTUAL_DISK_VERSION_UNSPECIFIED = 0,
  COMPACT_VIRTUAL_DISK_VERSION_1 = 1,
}

export enum CREATE_VIRTUAL_DISK_FLAG {
  CREATE_VIRTUAL_DISK_FLAG_NONE = 0x0000_0000,
  CREATE_VIRTUAL_DISK_FLAG_FULL_PHYSICAL_ALLOCATION = 0x0000_0001,
  CREATE_VIRTUAL_DISK_FLAG_PREVENT_WRITES_TO_SOURCE_DISK = 0x0000_0002,
  CREATE_VIRTUAL_DISK_FLAG_DO_NOT_COPY_METADATA_FROM_PARENT = 0x0000_0004,
  CREATE_VIRTUAL_DISK_FLAG_CREATE_BACKING_STORAGE = 0x0000_0008,
  CREATE_VIRTUAL_DISK_FLAG_USE_CHANGE_TRACKING_SOURCE_LIMIT = 0x0000_0010,
  CREATE_VIRTUAL_DISK_FLAG_PRESERVE_PARENT_CHANGE_TRACKING_STATE = 0x0000_0020,
  CREATE_VIRTUAL_DISK_FLAG_VHD_SET_USE_ORIGINAL_BACKING_STORAGE = 0x0000_0040,
  CREATE_VIRTUAL_DISK_FLAG_SPARSE_FILE = 0x0000_0080,
  CREATE_VIRTUAL_DISK_FLAG_PMEM_COMPATIBLE = 0x0000_0100,
  CREATE_VIRTUAL_DISK_FLAG_SUPPORT_COMPRESSED_VOLUMES = 0x0000_0200,
  CREATE_VIRTUAL_DISK_FLAG_SUPPORT_SPARSE_FILES_ANY_FS = 0x0000_0400,
}

export enum CREATE_VIRTUAL_DISK_VERSION {
  CREATE_VIRTUAL_DISK_VERSION_UNSPECIFIED = 0,
  CREATE_VIRTUAL_DISK_VERSION_1 = 1,
  CREATE_VIRTUAL_DISK_VERSION_2 = 2,
  CREATE_VIRTUAL_DISK_VERSION_3 = 3,
  CREATE_VIRTUAL_DISK_VERSION_4 = 4,
}

export enum DELETE_SNAPSHOT_VHDSET_FLAG {
  DELETE_SNAPSHOT_VHDSET_FLAG_NONE = 0x0000_0000,
  DELETE_SNAPSHOT_VHDSET_FLAG_PERSIST_RCT = 0x0000_0001,
}

export enum DELETE_SNAPSHOT_VHDSET_VERSION {
  DELETE_SNAPSHOT_VHDSET_VERSION_UNSPECIFIED = 0,
  DELETE_SNAPSHOT_VHDSET_VERSION_1 = 1,
}

export enum DEPENDENT_DISK_FLAG {
  DEPENDENT_DISK_FLAG_NONE = 0x0000_0000,
  DEPENDENT_DISK_FLAG_MULT_BACKING_FILES = 0x0000_0001,
  DEPENDENT_DISK_FLAG_FULLY_ALLOCATED = 0x0000_0002,
  DEPENDENT_DISK_FLAG_READ_ONLY = 0x0000_0004,
  DEPENDENT_DISK_FLAG_REMOTE = 0x0000_0008,
  DEPENDENT_DISK_FLAG_SYSTEM_VOLUME = 0x0000_0010,
  DEPENDENT_DISK_FLAG_SYSTEM_VOLUME_PARENT = 0x0000_0020,
  DEPENDENT_DISK_FLAG_REMOVABLE = 0x0000_0040,
  DEPENDENT_DISK_FLAG_NO_DRIVE_LETTER = 0x0000_0080,
  DEPENDENT_DISK_FLAG_PARENT = 0x0000_0100,
  DEPENDENT_DISK_FLAG_NO_HOST_DISK = 0x0000_0200,
  DEPENDENT_DISK_FLAG_PERMANENT_LIFETIME = 0x0000_0400,
  DEPENDENT_DISK_FLAG_SUPPORT_COMPRESSED_VOLUMES = 0x0000_0800,
  DEPENDENT_DISK_FLAG_ALWAYS_ALLOW_SPARSE = 0x0000_1000,
  DEPENDENT_DISK_FLAG_SUPPORT_ENCRYPTED_FILES = 0x0000_2000,
}

export enum DETACH_VIRTUAL_DISK_FLAG {
  DETACH_VIRTUAL_DISK_FLAG_NONE = 0x0000_0000,
}

export enum EXPAND_VIRTUAL_DISK_FLAG {
  EXPAND_VIRTUAL_DISK_FLAG_NONE = 0x0000_0000,
  EXPAND_VIRTUAL_DISK_FLAG_NOTIFY_CHANGE = 0x0000_0001,
}

export enum EXPAND_VIRTUAL_DISK_VERSION {
  EXPAND_VIRTUAL_DISK_VERSION_UNSPECIFIED = 0,
  EXPAND_VIRTUAL_DISK_VERSION_1 = 1,
}

export enum FORK_VIRTUAL_DISK_FLAG {
  FORK_VIRTUAL_DISK_FLAG_NONE = 0x0000_0000,
  FORK_VIRTUAL_DISK_FLAG_EXISTING_FILE = 0x0000_0001,
}

export enum FORK_VIRTUAL_DISK_VERSION {
  FORK_VIRTUAL_DISK_VERSION_UNSPECIFIED = 0,
  FORK_VIRTUAL_DISK_VERSION_1 = 1,
}

export enum GET_STORAGE_DEPENDENCY_FLAG {
  GET_STORAGE_DEPENDENCY_FLAG_NONE = 0x0000_0000,
  GET_STORAGE_DEPENDENCY_FLAG_HOST_VOLUMES = 0x0000_0001,
  GET_STORAGE_DEPENDENCY_FLAG_DISK_HANDLE = 0x0000_0002,
}

export enum GET_VIRTUAL_DISK_INFO_VERSION {
  GET_VIRTUAL_DISK_INFO_UNSPECIFIED = 0,
  GET_VIRTUAL_DISK_INFO_SIZE = 1,
  GET_VIRTUAL_DISK_INFO_IDENTIFIER = 2,
  GET_VIRTUAL_DISK_INFO_PARENT_LOCATION = 3,
  GET_VIRTUAL_DISK_INFO_PARENT_IDENTIFIER = 4,
  GET_VIRTUAL_DISK_INFO_PARENT_TIMESTAMP = 5,
  GET_VIRTUAL_DISK_INFO_VIRTUAL_STORAGE_TYPE = 6,
  GET_VIRTUAL_DISK_INFO_PROVIDER_SUBTYPE = 7,
  GET_VIRTUAL_DISK_INFO_IS_4K_ALIGNED = 8,
  GET_VIRTUAL_DISK_INFO_PHYSICAL_DISK = 9,
  GET_VIRTUAL_DISK_INFO_VHD_PHYSICAL_SECTOR_SIZE = 10,
  GET_VIRTUAL_DISK_INFO_SMALLEST_SAFE_VIRTUAL_SIZE = 11,
  GET_VIRTUAL_DISK_INFO_FRAGMENTATION = 12,
  GET_VIRTUAL_DISK_INFO_IS_LOADED = 13,
  GET_VIRTUAL_DISK_INFO_VIRTUAL_DISK_ID = 14,
  GET_VIRTUAL_DISK_INFO_CHANGE_TRACKING_STATE = 15,
}

export enum MERGE_VIRTUAL_DISK_FLAG {
  MERGE_VIRTUAL_DISK_FLAG_NONE = 0x0000_0000,
}

export enum MERGE_VIRTUAL_DISK_VERSION {
  MERGE_VIRTUAL_DISK_VERSION_UNSPECIFIED = 0,
  MERGE_VIRTUAL_DISK_VERSION_1 = 1,
  MERGE_VIRTUAL_DISK_VERSION_2 = 2,
}

export enum MIRROR_VIRTUAL_DISK_FLAG {
  MIRROR_VIRTUAL_DISK_FLAG_NONE = 0x0000_0000,
  MIRROR_VIRTUAL_DISK_FLAG_EXISTING_FILE = 0x0000_0001,
  MIRROR_VIRTUAL_DISK_FLAG_SKIP_MIRROR_ACTIVATION = 0x0000_0002,
  MIRROR_VIRTUAL_DISK_FLAG_ENABLE_SMB_COMPRESSION = 0x0000_0004,
  MIRROR_VIRTUAL_DISK_FLAG_IS_LIVE_MIGRATION = 0x0000_0008,
}

export enum MIRROR_VIRTUAL_DISK_VERSION {
  MIRROR_VIRTUAL_DISK_VERSION_UNSPECIFIED = 0,
  MIRROR_VIRTUAL_DISK_VERSION_1 = 1,
}

export enum MODIFY_VHDSET_FLAG {
  MODIFY_VHDSET_FLAG_NONE = 0x0000_0000,
  MODIFY_VHDSET_FLAG_WRITEABLE_SNAPSHOT = 0x0000_0001,
}

export enum MODIFY_VHDSET_VERSION {
  MODIFY_VHDSET_UNSPECIFIED = 0,
  MODIFY_VHDSET_SNAPSHOT_PATH = 1,
  MODIFY_VHDSET_REMOVE_SNAPSHOT = 2,
  MODIFY_VHDSET_DEFAULT_SNAPSHOT_PATH = 3,
}

export enum OPEN_VIRTUAL_DISK_FLAG {
  OPEN_VIRTUAL_DISK_FLAG_NONE = 0x0000_0000,
  OPEN_VIRTUAL_DISK_FLAG_NO_PARENTS = 0x0000_0001,
  OPEN_VIRTUAL_DISK_FLAG_BLANK_FILE = 0x0000_0002,
  OPEN_VIRTUAL_DISK_FLAG_BOOT_DRIVE = 0x0000_0004,
  OPEN_VIRTUAL_DISK_FLAG_CACHED_IO = 0x0000_0008,
  OPEN_VIRTUAL_DISK_FLAG_CUSTOM_DIFF_CHAIN = 0x0000_0010,
  OPEN_VIRTUAL_DISK_FLAG_PARENT_CACHED_IO = 0x0000_0020,
  OPEN_VIRTUAL_DISK_FLAG_VHDSET_FILE_ONLY = 0x0000_0040,
  OPEN_VIRTUAL_DISK_FLAG_IGNORE_RELATIVE_PARENT_LOCATOR = 0x0000_0080,
  OPEN_VIRTUAL_DISK_FLAG_NO_WRITE_HARDENING = 0x0000_0100,
  OPEN_VIRTUAL_DISK_FLAG_SUPPORT_COMPRESSED_VOLUMES = 0x0000_0200,
  OPEN_VIRTUAL_DISK_FLAG_SUPPORT_SPARSE_FILES_ANY_FS = 0x0000_0400,
  OPEN_VIRTUAL_DISK_FLAG_SUPPORT_ENCRYPTED_FILES = 0x0000_0800,
}

export enum OPEN_VIRTUAL_DISK_VERSION {
  OPEN_VIRTUAL_DISK_VERSION_UNSPECIFIED = 0,
  OPEN_VIRTUAL_DISK_VERSION_1 = 1,
  OPEN_VIRTUAL_DISK_VERSION_2 = 2,
  OPEN_VIRTUAL_DISK_VERSION_3 = 3,
}

export enum QUERY_CHANGES_VIRTUAL_DISK_FLAG {
  QUERY_CHANGES_VIRTUAL_DISK_FLAG_NONE = 0x0000_0000,
}

export enum RAW_SCSI_VIRTUAL_DISK_FLAG {
  RAW_SCSI_VIRTUAL_DISK_FLAG_NONE = 0x0000_0000,
}

export enum RAW_SCSI_VIRTUAL_DISK_VERSION {
  RAW_SCSI_VIRTUAL_DISK_VERSION_UNSPECIFIED = 0,
  RAW_SCSI_VIRTUAL_DISK_VERSION_1 = 1,
}

export enum RESIZE_VIRTUAL_DISK_FLAG {
  RESIZE_VIRTUAL_DISK_FLAG_NONE = 0x0000_0000,
  RESIZE_VIRTUAL_DISK_FLAG_ALLOW_UNSAFE_VIRTUAL_SIZE = 0x0000_0001,
  RESIZE_VIRTUAL_DISK_FLAG_RESIZE_TO_SMALLEST_SAFE_VIRTUAL_SIZE = 0x0000_0002,
}

export enum RESIZE_VIRTUAL_DISK_VERSION {
  RESIZE_VIRTUAL_DISK_VERSION_UNSPECIFIED = 0,
  RESIZE_VIRTUAL_DISK_VERSION_1 = 1,
}

export enum SET_VIRTUAL_DISK_INFO_VERSION {
  SET_VIRTUAL_DISK_INFO_UNSPECIFIED = 0,
  SET_VIRTUAL_DISK_INFO_PARENT_PATH = 1,
  SET_VIRTUAL_DISK_INFO_IDENTIFIER = 2,
  SET_VIRTUAL_DISK_INFO_PARENT_PATH_WITH_DEPTH = 3,
  SET_VIRTUAL_DISK_INFO_PHYSICAL_SECTOR_SIZE = 4,
  SET_VIRTUAL_DISK_INFO_VIRTUAL_DISK_ID = 5,
  SET_VIRTUAL_DISK_INFO_CHANGE_TRACKING_STATE = 6,
  SET_VIRTUAL_DISK_INFO_PARENT_LOCATOR = 7,
}

export enum STORAGE_DEPENDENCY_INFO_VERSION {
  STORAGE_DEPENDENCY_INFO_VERSION_UNSPECIFIED = 0,
  STORAGE_DEPENDENCY_INFO_VERSION_1 = 1,
  STORAGE_DEPENDENCY_INFO_VERSION_2 = 2,
}

export enum TAKE_SNAPSHOT_VHDSET_FLAG {
  TAKE_SNAPSHOT_VHDSET_FLAG_NONE = 0x0000_0000,
  TAKE_SNAPSHOT_VHDSET_FLAG_WRITEABLE = 0x0000_0001,
}

export enum TAKE_SNAPSHOT_VHDSET_VERSION {
  TAKE_SNAPSHOT_VHDSET_VERSION_UNSPECIFIED = 0,
  TAKE_SNAPSHOT_VHDSET_VERSION_1 = 1,
}

export enum VIRTUAL_DISK_ACCESS_MASK {
  VIRTUAL_DISK_ACCESS_NONE = 0x0000_0000,
  VIRTUAL_DISK_ACCESS_ATTACH_RO = 0x0001_0000,
  VIRTUAL_DISK_ACCESS_ATTACH_RW = 0x0002_0000,
  VIRTUAL_DISK_ACCESS_DETACH = 0x0004_0000,
  VIRTUAL_DISK_ACCESS_GET_INFO = 0x0008_0000,
  VIRTUAL_DISK_ACCESS_CREATE = 0x0010_0000,
  VIRTUAL_DISK_ACCESS_METAOPS = 0x0020_0000,
  VIRTUAL_DISK_ACCESS_READ = 0x000d_0000,
  VIRTUAL_DISK_ACCESS_ALL = 0x003f_0000,
  VIRTUAL_DISK_ACCESS_WRITABLE = 0x0032_0000,
}

export type LPOVERLAPPED = Pointer;
export type PAPPLY_SNAPSHOT_VHDSET_PARAMETERS = Pointer;
export type PATTACH_VIRTUAL_DISK_PARAMETERS = Pointer;
export type PCOMPACT_VIRTUAL_DISK_PARAMETERS = Pointer;
export type PCREATE_VIRTUAL_DISK_PARAMETERS = Pointer;
export type PDELETE_SNAPSHOT_VHDSET_PARAMETERS = Pointer;
export type PEXPAND_VIRTUAL_DISK_PARAMETERS = Pointer;
export type PFORK_VIRTUAL_DISK_PARAMETERS = Pointer;
export type PGET_VIRTUAL_DISK_INFO = Pointer;
export type PGUID = Pointer;
export type PMERGE_VIRTUAL_DISK_PARAMETERS = Pointer;
export type PMIRROR_VIRTUAL_DISK_PARAMETERS = Pointer;
export type PMODIFY_VHDSET_PARAMETERS = Pointer;
export type POPEN_VIRTUAL_DISK_PARAMETERS = Pointer;
export type PQUERY_CHANGES_VIRTUAL_DISK_RANGE = Pointer;
export type PRAW_SCSI_VIRTUAL_DISK_PARAMETERS = Pointer;
export type PRAW_SCSI_VIRTUAL_DISK_RESPONSE = Pointer;
export type PRESIZE_VIRTUAL_DISK_PARAMETERS = Pointer;
export type PSECURITY_DESCRIPTOR = Pointer;
export type PSET_VIRTUAL_DISK_INFO = Pointer;
export type PSTORAGE_DEPENDENCY_INFO = Pointer;
export type PTAKE_SNAPSHOT_VHDSET_PARAMETERS = Pointer;
export type PULONG64 = Pointer;
export type PVIRTUAL_DISK_PROGRESS = Pointer;
export type PVIRTUAL_STORAGE_TYPE = Pointer;

export type ULONG64 = bigint;
