import type { Pointer } from 'bun:ffi';

export type { DWORD, HANDLE, INT, LPCWSTR, LPVOID, NULL, Optional, PHANDLE, PULONG, PVOID, ULONG } from '@bun-win32/core';

export const FWPM_FILTER_FLAG_BOOTTIME = 0x0000_0002;
export const FWPM_FILTER_FLAG_NONE = 0x0000_0000;
export const FWPM_FILTER_FLAG_PERSISTENT = 0x0000_0001;
export const FWPM_SESSION_FLAG_DYNAMIC = 0x0000_0001;
export const FWPM_TUNNEL_FLAG_ENABLE_VIRTUAL_IF_TUNNELING = 0x0000_0002;
export const FWPM_TUNNEL_FLAG_POINT_TO_POINT = 0x0000_0001;
export const FWPM_TUNNEL_FLAG_RESERVED0 = 0x0000_0004;
export const FWPM_TXN_READ_ONLY = 0x0000_0001;
export const RPC_C_AUTHN_DEFAULT = 0xffff_ffff;
export const RPC_C_AUTHN_WINNT = 0x0000_000a;

export enum FWPM_ENGINE_OPTION {
  FWPM_ENGINE_COLLECT_NET_EVENTS = 0,
  FWPM_ENGINE_MONITOR_IPSEC_CONNECTIONS = 3,
  FWPM_ENGINE_NAME_CACHE = 2,
  FWPM_ENGINE_NET_EVENT_MATCH_ANY_KEYWORDS = 1,
  FWPM_ENGINE_OPTION_MAX = 6,
  FWPM_ENGINE_PACKET_QUEUING = 4,
  FWPM_ENGINE_TXN_WATCHDOG_TIMEOUT_IN_MSEC = 5,
}

export type IPSEC_SA_SPI = number;
export type LUID = bigint;
export type SECURITY_INFORMATION = number;
export type SOCKET = bigint;
export type UINT16 = number;
export type UINT32 = number;
export type UINT64 = bigint;
export type FWPM_CALLOUT_CHANGE_CALLBACK0 = Pointer;
export type FWPM_CONNECTION_CALLBACK0 = Pointer;
export type FWPM_DYNAMIC_KEYWORD_CALLBACK0 = Pointer;
export type FWPM_FILTER_CHANGE_CALLBACK0 = Pointer;
export type FWPM_NET_EVENT_CALLBACK0 = Pointer;
export type FWPM_NET_EVENT_CALLBACK1 = Pointer;
export type FWPM_NET_EVENT_CALLBACK2 = Pointer;
export type FWPM_NET_EVENT_CALLBACK3 = Pointer;
export type FWPM_NET_EVENT_CALLBACK4 = Pointer;
export type FWPM_PROVIDER_CHANGE_CALLBACK0 = Pointer;
export type FWPM_PROVIDER_CONTEXT_CHANGE_CALLBACK0 = Pointer;
export type FWPM_SUBLAYER_CHANGE_CALLBACK0 = Pointer;
export type FWPM_SYSTEM_PORTS_CALLBACK0 = Pointer;
export type FWPM_VSWITCH_EVENT_CALLBACK0 = Pointer;
export type IPSEC_SA_CONTEXT_CALLBACK0 = Pointer;
export type LPGUID = Pointer;
export type LPWSAOVERLAPPED = Pointer;
export type LPWSAOVERLAPPED_COMPLETION_ROUTINE = Pointer;
export type PACL = Pointer;
export type PFWPM_CALLOUT0 = Pointer;
export type PFWPM_CALLOUT_ENUM_TEMPLATE0 = Pointer;
export type PFWPM_CALLOUT_SUBSCRIPTION0 = Pointer;
export type PFWPM_CONNECTION0 = Pointer;
export type PFWPM_CONNECTION_ENUM_TEMPLATE0 = Pointer;
export type PFWPM_CONNECTION_SUBSCRIPTION0 = Pointer;
export type PFWPM_FILTER0 = Pointer;
export type PFWPM_FILTER_CONDITION0 = Pointer;
export type PFWPM_FILTER_ENUM_TEMPLATE0 = Pointer;
export type PFWPM_FILTER_SUBSCRIPTION0 = Pointer;
export type PFWPM_LAYER0 = Pointer;
export type PFWPM_LAYER_ENUM_TEMPLATE0 = Pointer;
export type PFWPM_NET_EVENT0 = Pointer;
export type PFWPM_NET_EVENT1 = Pointer;
export type PFWPM_NET_EVENT2 = Pointer;
export type PFWPM_NET_EVENT3 = Pointer;
export type PFWPM_NET_EVENT4 = Pointer;
export type PFWPM_NET_EVENT5 = Pointer;
export type PFWPM_NET_EVENT_ENUM_TEMPLATE0 = Pointer;
export type PFWPM_NET_EVENT_SUBSCRIPTION0 = Pointer;
export type PFWPM_PROVIDER0 = Pointer;
export type PFWPM_PROVIDER_CONTEXT0 = Pointer;
export type PFWPM_PROVIDER_CONTEXT1 = Pointer;
export type PFWPM_PROVIDER_CONTEXT2 = Pointer;
export type PFWPM_PROVIDER_CONTEXT3 = Pointer;
export type PFWPM_PROVIDER_CONTEXT_ENUM_TEMPLATE0 = Pointer;
export type PFWPM_PROVIDER_CONTEXT_SUBSCRIPTION0 = Pointer;
export type PFWPM_PROVIDER_ENUM_TEMPLATE0 = Pointer;
export type PFWPM_PROVIDER_SUBSCRIPTION0 = Pointer;
export type PFWPM_SESSION0 = Pointer;
export type PFWPM_SESSION_ENUM_TEMPLATE0 = Pointer;
export type PFWPM_SUBLAYER0 = Pointer;
export type PFWPM_SUBLAYER_ENUM_TEMPLATE0 = Pointer;
export type PFWPM_SUBLAYER_SUBSCRIPTION0 = Pointer;
export type PFWPM_SYSTEM_PORTS0 = Pointer;
export type PFWPM_VSWITCH_EVENT_SUBSCRIPTION0 = Pointer;
export type PFWPS_ALE_ENDPOINT_ENUM_TEMPLATE0 = Pointer;
export type PFWPS_ALE_ENDPOINT_PROPERTIES0 = Pointer;
export type PFWP_BYTE_BLOB = Pointer;
export type PFWP_VALUE0 = Pointer;
export type PIKEEXT_SA_DETAILS0 = Pointer;
export type PIKEEXT_SA_DETAILS1 = Pointer;
export type PIKEEXT_SA_DETAILS2 = Pointer;
export type PIKEEXT_SA_ENUM_TEMPLATE0 = Pointer;
export type PIKEEXT_STATISTICS0 = Pointer;
export type PIKEEXT_STATISTICS1 = Pointer;
export type PIPSEC_DOSP_STATE0 = Pointer;
export type PIPSEC_DOSP_STATE_ENUM_TEMPLATE0 = Pointer;
export type PIPSEC_DOSP_STATISTICS0 = Pointer;
export type PIPSEC_GETSPI0 = Pointer;
export type PIPSEC_GETSPI1 = Pointer;
export type PIPSEC_KEY_MANAGER0 = Pointer;
export type PIPSEC_KEY_MANAGER_CALLBACKS0 = Pointer;
export type PIPSEC_SA_BUNDLE0 = Pointer;
export type PIPSEC_SA_BUNDLE1 = Pointer;
export type PIPSEC_SA_CONTEXT0 = Pointer;
export type PIPSEC_SA_CONTEXT1 = Pointer;
export type PIPSEC_SA_CONTEXT_ENUM_TEMPLATE0 = Pointer;
export type PIPSEC_SA_CONTEXT_SUBSCRIPTION0 = Pointer;
export type PIPSEC_SA_DETAILS0 = Pointer;
export type PIPSEC_SA_DETAILS1 = Pointer;
export type PIPSEC_SA_ENUM_TEMPLATE0 = Pointer;
export type PIPSEC_SA_SPI = Pointer;
export type PIPSEC_STATISTICS0 = Pointer;
export type PIPSEC_STATISTICS1 = Pointer;
export type PIPSEC_TRAFFIC0 = Pointer;
export type PIPSEC_TRAFFIC1 = Pointer;
export type PIPSEC_VIRTUAL_IF_TUNNEL_INFO0 = Pointer;
export type PSECURITY_DESCRIPTOR = Pointer;
export type PSEC_WINNT_AUTH_IDENTITY_W = Pointer;
export type PSID = Pointer;
export type PSOCKADDR = Pointer;
export type PSOCKET_PEER_TARGET_NAME = Pointer;
export type PSOCKET_SECURITY_QUERY_INFO = Pointer;
export type PSOCKET_SECURITY_QUERY_TEMPLATE = Pointer;
export type PSOCKET_SECURITY_SETTINGS = Pointer;
export type PUINT32 = Pointer;
export type PUINT64 = Pointer;
