import type { Pointer } from 'bun:ffi';

import type { DWORD } from '@bun-win32/core';
export type { BOOL, BYTE, DWORD, HANDLE, LPCWSTR, LPDWORD, LPHANDLE, LPWSTR, NULL, Optional, PBYTE, PDWORD, PHANDLE, PULONG, PVOID, ULONG, VOID } from '@bun-win32/core';

export const WLAN_API_VERSION = 0x0000_0002;
export const WLAN_API_VERSION_1_0 = 0x0000_0001;
export const WLAN_API_VERSION_2_0 = 0x0000_0002;

export enum Dot11BssType {
  DOT11_BSS_TYPE_INFRASTRUCTURE = 1,
  DOT11_BSS_TYPE_INDEPENDENT = 2,
  DOT11_BSS_TYPE_ANY = 3,
}

export enum WlanAutoconfOpcode {
  WLAN_AUTOCONF_OPCODE_START = 0,
  WLAN_AUTOCONF_OPCODE_SHOW_DENIED_NETWORKS = 1,
  WLAN_AUTOCONF_OPCODE_POWER_SETTING = 2,
  WLAN_AUTOCONF_OPCODE_ONLY_USE_GP_PROFILES_FOR_ALLOWED_NETWORKS = 3,
  WLAN_AUTOCONF_OPCODE_ALLOW_EXPLICIT_CREDS = 4,
  WLAN_AUTOCONF_OPCODE_BLOCK_PERIOD = 5,
  WLAN_AUTOCONF_OPCODE_ALLOW_VIRTUAL_STATION_EXTENSIBILITY = 6,
  WLAN_AUTOCONF_OPCODE_END = 7,
}

export enum WlanFilterListType {
  WLAN_FILTER_LIST_TYPE_GP_PERMIT = 0,
  WLAN_FILTER_LIST_TYPE_GP_DENY = 1,
  WLAN_FILTER_LIST_TYPE_USER_PERMIT = 2,
  WLAN_FILTER_LIST_TYPE_USER_DENY = 3,
}

export enum WlanHostedNetworkOpcode {
  WLAN_HOSTED_NETWORK_OPCODE_CONNECTION_SETTINGS = 0,
  WLAN_HOSTED_NETWORK_OPCODE_SECURITY_SETTINGS = 1,
  WLAN_HOSTED_NETWORK_OPCODE_STATION_PROFILE = 2,
  WLAN_HOSTED_NETWORK_OPCODE_ENABLE = 3,
}

export enum WlanHostedNetworkReason {
  WLAN_HOSTED_NETWORK_REASON_SUCCESS = 0,
  WLAN_HOSTED_NETWORK_REASON_UNSPECIFIED = 1,
  WLAN_HOSTED_NETWORK_REASON_BAD_PARAMETERS = 2,
  WLAN_HOSTED_NETWORK_REASON_SERVICE_SHUTTING_DOWN = 3,
  WLAN_HOSTED_NETWORK_REASON_INSUFFICIENT_RESOURCES = 4,
  WLAN_HOSTED_NETWORK_REASON_ELEVATION_REQUIRED = 5,
  WLAN_HOSTED_NETWORK_REASON_READ_ONLY = 6,
  WLAN_HOSTED_NETWORK_REASON_PERSISTENCE_FAILED = 7,
  WLAN_HOSTED_NETWORK_REASON_CRYPT_ERROR = 8,
  WLAN_HOSTED_NETWORK_REASON_IMPERSONATION = 9,
  WLAN_HOSTED_NETWORK_REASON_STOP_BEFORE_START = 10,
  WLAN_HOSTED_NETWORK_REASON_INTERFACE_AVAILABLE = 11,
  WLAN_HOSTED_NETWORK_REASON_INTERFACE_UNAVAILABLE = 12,
  WLAN_HOSTED_NETWORK_REASON_MINIPORT_STOPPED = 13,
  WLAN_HOSTED_NETWORK_REASON_MINIPORT_STARTED = 14,
  WLAN_HOSTED_NETWORK_REASON_INCOMPATIBLE_CONNECTION_STARTED = 15,
  WLAN_HOSTED_NETWORK_REASON_INCOMPATIBLE_CONNECTION_STOPPED = 16,
  WLAN_HOSTED_NETWORK_REASON_USER_ACTION = 17,
  WLAN_HOSTED_NETWORK_REASON_CLIENT_ABORT = 18,
  WLAN_HOSTED_NETWORK_REASON_AP_START_FAILED = 19,
  WLAN_HOSTED_NETWORK_REASON_PEER_ARRIVED = 20,
  WLAN_HOSTED_NETWORK_REASON_PEER_DEPARTED = 21,
  WLAN_HOSTED_NETWORK_REASON_PEER_TIMEOUT = 22,
  WLAN_HOSTED_NETWORK_REASON_GP_DENIED = 23,
  WLAN_HOSTED_NETWORK_REASON_SERVICE_UNAVAILABLE = 24,
  WLAN_HOSTED_NETWORK_REASON_DEVICE_CHANGE = 25,
  WLAN_HOSTED_NETWORK_REASON_PROPERTIES_CHANGE = 26,
  WLAN_HOSTED_NETWORK_REASON_VIRTUAL_STATION_BLOCKING_USE = 27,
  WLAN_HOSTED_NETWORK_REASON_SERVICE_AVAILABLE_ON_VIRTUAL_STATION = 28,
}

export enum WlanIhvControlType {
  WLAN_IHV_CONTROL_TYPE_SERVICE = 0,
  WLAN_IHV_CONTROL_TYPE_DRIVER = 1,
}

export enum WlanIntfOpcode {
  WLAN_INTF_OPCODE_AUTOCONF_START = 0x0000_0000,
  WLAN_INTF_OPCODE_AUTOCONF_ENABLED = 0x0000_0001,
  WLAN_INTF_OPCODE_BACKGROUND_SCAN_ENABLED = 0x0000_0002,
  WLAN_INTF_OPCODE_MEDIA_STREAMING_MODE = 0x0000_0003,
  WLAN_INTF_OPCODE_RADIO_STATE = 0x0000_0004,
  WLAN_INTF_OPCODE_BSS_TYPE = 0x0000_0005,
  WLAN_INTF_OPCODE_INTERFACE_STATE = 0x0000_0006,
  WLAN_INTF_OPCODE_CURRENT_CONNECTION = 0x0000_0007,
  WLAN_INTF_OPCODE_CHANNEL_NUMBER = 0x0000_0008,
  WLAN_INTF_OPCODE_SUPPORTED_INFRASTRUCTURE_AUTH_CIPHER_PAIRS = 0x0000_0009,
  WLAN_INTF_OPCODE_SUPPORTED_ADHOC_AUTH_CIPHER_PAIRS = 0x0000_000a,
  WLAN_INTF_OPCODE_SUPPORTED_COUNTRY_OR_REGION_STRING_LIST = 0x0000_000b,
  WLAN_INTF_OPCODE_CURRENT_OPERATION_MODE = 0x0000_000c,
  WLAN_INTF_OPCODE_SUPPORTED_SAFE_MODE = 0x0000_000d,
  WLAN_INTF_OPCODE_CERTIFIED_SAFE_MODE = 0x0000_000e,
  WLAN_INTF_OPCODE_HOSTED_NETWORK_CAPABLE = 0x0000_000f,
  WLAN_INTF_OPCODE_MANAGEMENT_FRAME_PROTECTION_CAPABLE = 0x0000_0010,
  WLAN_INTF_OPCODE_SECONDARY_STA_INTERFACES = 0x0000_0011,
  WLAN_INTF_OPCODE_SECONDARY_STA_SYNCHRONIZED_CONNECTIONS = 0x0000_0012,
  WLAN_INTF_OPCODE_AUTOCONF_END = 0x0fff_ffff,
  WLAN_INTF_OPCODE_MSM_START = 0x1000_0100,
  WLAN_INTF_OPCODE_STATISTICS = 0x1000_0101,
  WLAN_INTF_OPCODE_RSSI = 0x1000_0102,
  WLAN_INTF_OPCODE_MSM_END = 0x1fff_ffff,
  WLAN_INTF_OPCODE_SECURITY_START = 0x2001_0000,
  WLAN_INTF_OPCODE_SECURITY_END = 0x2fff_ffff,
  WLAN_INTF_OPCODE_IHV_START = 0x3000_0000,
  WLAN_INTF_OPCODE_IHV_END = 0x3fff_ffff,
}

export enum WlanOpcodeValueType {
  WLAN_OPCODE_VALUE_TYPE_QUERY_ONLY = 0,
  WLAN_OPCODE_VALUE_TYPE_SET_BY_GROUP_POLICY = 1,
  WLAN_OPCODE_VALUE_TYPE_SET_BY_USER = 2,
  WLAN_OPCODE_VALUE_TYPE_INVALID = 3,
}

export enum WlanSecurableObject {
  WLAN_SECURE_PERMIT_LIST = 0,
  WLAN_SECURE_DENY_LIST = 1,
  WLAN_SECURE_AC_ENABLED = 2,
  WLAN_SECURE_BC_SCAN_ENABLED = 3,
  WLAN_SECURE_BSS_TYPE = 4,
  WLAN_SECURE_SHOW_DENIED = 5,
  WLAN_SECURE_INTERFACE_PROPERTIES = 6,
  WLAN_SECURE_IHV_CONTROL = 7,
  WLAN_SECURE_ALL_USER_PROFILES_ORDER = 8,
  WLAN_SECURE_ADD_NEW_ALL_USER_PROFILES = 9,
  WLAN_SECURE_ADD_NEW_PER_USER_PROFILES = 10,
  WLAN_SECURE_MEDIA_STREAMING_MODE_ENABLED = 11,
  WLAN_SECURE_CURRENT_OPERATION_MODE = 12,
  WLAN_SECURE_GET_PLAINTEXT_KEY = 13,
  WLAN_SECURE_HOSTED_NETWORK_ELEVATED_ACCESS = 14,
  WLAN_SECURE_VIRTUAL_STATION_EXTENSIBILITY = 15,
  WLAN_SECURE_WFD_ELEVATED_ACCESS = 16,
  WLAN_SECURABLE_OBJECT_COUNT = 17,
}

export type EAP_METHOD_TYPE = Pointer;
export type LPCGUID = Pointer;
export type LPGUID = Pointer;
export type PBOOL = Pointer;
export type PDOT11_MAC_ADDRESS = Pointer;
export type PDOT11_NETWORK_LIST = Pointer;
export type PDOT11_SSID = Pointer;
export type PLPCWSTR = Pointer;
export type PPBYTE = Pointer;
export type PPVOID = Pointer;
export type PWCHAR = Pointer;
export type PWLAN_AVAILABLE_NETWORK_LIST = Pointer;
export type PWLAN_BSS_LIST = Pointer;
export type PWLAN_CONNECTION_PARAMETERS = Pointer;
export type PWLAN_DEVICE_SERVICE_GUID_LIST = Pointer;
export type PWLAN_HOSTED_NETWORK_REASON = Pointer;
export type PWLAN_HOSTED_NETWORK_STATUS = Pointer;
export type PWLAN_INTERFACE_CAPABILITY = Pointer;
export type PWLAN_INTERFACE_INFO_LIST = Pointer;
export type PWLAN_OPCODE_VALUE_TYPE = Pointer;
export type PWLAN_PROFILE_INFO_LIST = Pointer;
export type PWLAN_RAW_DATA = Pointer;
export type PWLAN_RAW_DATA_LIST = Pointer;
export type PZPWSTR = Pointer;
export type WFD_OPEN_SESSION_COMPLETE_CALLBACK = Pointer;
export type WLAN_NOTIFICATION_CALLBACK = Pointer;
export type WLAN_REASON_CODE = DWORD;
