import type { Pointer } from 'bun:ffi';

export type { DWORD, HRESULT, HWND, LPBOOL, LPCWSTR, NULL, Optional } from '@bun-win32/core';

export const WEBAUTHN_API_VERSION_1 = 1;
export const WEBAUTHN_API_VERSION_2 = 2;
export const WEBAUTHN_API_VERSION_3 = 3;
export const WEBAUTHN_API_VERSION_4 = 4;
export const WEBAUTHN_API_VERSION_5 = 5;
export const WEBAUTHN_API_VERSION_6 = 6;
export const WEBAUTHN_API_VERSION_7 = 7;
export const WEBAUTHN_API_VERSION_8 = 8;
export const WEBAUTHN_API_VERSION_9 = 9;
export const WEBAUTHN_API_CURRENT_VERSION = WEBAUTHN_API_VERSION_9;

export const WEBAUTHN_RP_ENTITY_INFORMATION_CURRENT_VERSION = 1;
export const WEBAUTHN_USER_ENTITY_INFORMATION_CURRENT_VERSION = 1;
export const WEBAUTHN_CLIENT_DATA_CURRENT_VERSION = 1;
export const WEBAUTHN_COSE_CREDENTIAL_PARAMETER_CURRENT_VERSION = 1;
export const WEBAUTHN_CREDENTIAL_CURRENT_VERSION = 1;
export const WEBAUTHN_CREDENTIAL_EX_CURRENT_VERSION = 1;
export const WEBAUTHN_COMMON_ATTESTATION_CURRENT_VERSION = 1;
export const WEBAUTHN_GET_CREDENTIALS_OPTIONS_CURRENT_VERSION = 1;
export const WEBAUTHN_AUTHENTICATOR_DETAILS_OPTIONS_CURRENT_VERSION = 1;
export const WEBAUTHN_AUTHENTICATOR_DETAILS_CURRENT_VERSION = 1;
export const WEBAUTHN_CREDENTIAL_DETAILS_VERSION_1 = 1;
export const WEBAUTHN_CREDENTIAL_DETAILS_VERSION_2 = 2;
export const WEBAUTHN_CREDENTIAL_DETAILS_VERSION_3 = 3;
export const WEBAUTHN_CREDENTIAL_DETAILS_VERSION_4 = 4;
export const WEBAUTHN_CREDENTIAL_DETAILS_CURRENT_VERSION = WEBAUTHN_CREDENTIAL_DETAILS_VERSION_4;
export const WEBAUTHN_CREDENTIAL_ATTESTATION_VERSION_1 = 1;
export const WEBAUTHN_CREDENTIAL_ATTESTATION_VERSION_2 = 2;
export const WEBAUTHN_CREDENTIAL_ATTESTATION_VERSION_3 = 3;
export const WEBAUTHN_CREDENTIAL_ATTESTATION_VERSION_4 = 4;
export const WEBAUTHN_CREDENTIAL_ATTESTATION_VERSION_5 = 5;
export const WEBAUTHN_CREDENTIAL_ATTESTATION_VERSION_6 = 6;
export const WEBAUTHN_CREDENTIAL_ATTESTATION_VERSION_7 = 7;
export const WEBAUTHN_CREDENTIAL_ATTESTATION_VERSION_8 = 8;
export const WEBAUTHN_CREDENTIAL_ATTESTATION_CURRENT_VERSION = WEBAUTHN_CREDENTIAL_ATTESTATION_VERSION_8;
export const WEBAUTHN_ASSERTION_VERSION_1 = 1;
export const WEBAUTHN_ASSERTION_VERSION_2 = 2;
export const WEBAUTHN_ASSERTION_VERSION_3 = 3;
export const WEBAUTHN_ASSERTION_VERSION_4 = 4;
export const WEBAUTHN_ASSERTION_VERSION_5 = 5;
export const WEBAUTHN_ASSERTION_VERSION_6 = 6;
export const WEBAUTHN_ASSERTION_CURRENT_VERSION = WEBAUTHN_ASSERTION_VERSION_6;
export const WEBAUTHN_AUTHENTICATOR_MAKE_CREDENTIAL_OPTIONS_VERSION_1 = 1;
export const WEBAUTHN_AUTHENTICATOR_MAKE_CREDENTIAL_OPTIONS_VERSION_2 = 2;
export const WEBAUTHN_AUTHENTICATOR_MAKE_CREDENTIAL_OPTIONS_VERSION_3 = 3;
export const WEBAUTHN_AUTHENTICATOR_MAKE_CREDENTIAL_OPTIONS_VERSION_4 = 4;
export const WEBAUTHN_AUTHENTICATOR_MAKE_CREDENTIAL_OPTIONS_VERSION_5 = 5;
export const WEBAUTHN_AUTHENTICATOR_MAKE_CREDENTIAL_OPTIONS_VERSION_6 = 6;
export const WEBAUTHN_AUTHENTICATOR_MAKE_CREDENTIAL_OPTIONS_VERSION_7 = 7;
export const WEBAUTHN_AUTHENTICATOR_MAKE_CREDENTIAL_OPTIONS_VERSION_8 = 8;
export const WEBAUTHN_AUTHENTICATOR_MAKE_CREDENTIAL_OPTIONS_VERSION_9 = 9;
export const WEBAUTHN_AUTHENTICATOR_MAKE_CREDENTIAL_OPTIONS_CURRENT_VERSION = WEBAUTHN_AUTHENTICATOR_MAKE_CREDENTIAL_OPTIONS_VERSION_9;
export const WEBAUTHN_AUTHENTICATOR_GET_ASSERTION_OPTIONS_VERSION_1 = 1;
export const WEBAUTHN_AUTHENTICATOR_GET_ASSERTION_OPTIONS_VERSION_2 = 2;
export const WEBAUTHN_AUTHENTICATOR_GET_ASSERTION_OPTIONS_VERSION_3 = 3;
export const WEBAUTHN_AUTHENTICATOR_GET_ASSERTION_OPTIONS_VERSION_4 = 4;
export const WEBAUTHN_AUTHENTICATOR_GET_ASSERTION_OPTIONS_VERSION_5 = 5;
export const WEBAUTHN_AUTHENTICATOR_GET_ASSERTION_OPTIONS_VERSION_6 = 6;
export const WEBAUTHN_AUTHENTICATOR_GET_ASSERTION_OPTIONS_VERSION_7 = 7;
export const WEBAUTHN_AUTHENTICATOR_GET_ASSERTION_OPTIONS_VERSION_8 = 8;
export const WEBAUTHN_AUTHENTICATOR_GET_ASSERTION_OPTIONS_VERSION_9 = 9;
export const WEBAUTHN_AUTHENTICATOR_GET_ASSERTION_OPTIONS_CURRENT_VERSION = WEBAUTHN_AUTHENTICATOR_GET_ASSERTION_OPTIONS_VERSION_9;

export const WEBAUTHN_AUTHENTICATOR_ATTACHMENT_ANY = 0;
export const WEBAUTHN_AUTHENTICATOR_ATTACHMENT_PLATFORM = 1;
export const WEBAUTHN_AUTHENTICATOR_ATTACHMENT_CROSS_PLATFORM = 2;
export const WEBAUTHN_AUTHENTICATOR_ATTACHMENT_CROSS_PLATFORM_U2F_V2 = 3;

export const WEBAUTHN_USER_VERIFICATION_REQUIREMENT_ANY = 0;
export const WEBAUTHN_USER_VERIFICATION_REQUIREMENT_REQUIRED = 1;
export const WEBAUTHN_USER_VERIFICATION_REQUIREMENT_PREFERRED = 2;
export const WEBAUTHN_USER_VERIFICATION_REQUIREMENT_DISCOURAGED = 3;

export const WEBAUTHN_USER_VERIFICATION_ANY = 0;
export const WEBAUTHN_USER_VERIFICATION_OPTIONAL = 1;
export const WEBAUTHN_USER_VERIFICATION_OPTIONAL_WITH_CREDENTIAL_ID_LIST = 2;
export const WEBAUTHN_USER_VERIFICATION_REQUIRED = 3;

export const WEBAUTHN_ATTESTATION_CONVEYANCE_PREFERENCE_ANY = 0;
export const WEBAUTHN_ATTESTATION_CONVEYANCE_PREFERENCE_NONE = 1;
export const WEBAUTHN_ATTESTATION_CONVEYANCE_PREFERENCE_INDIRECT = 2;
export const WEBAUTHN_ATTESTATION_CONVEYANCE_PREFERENCE_DIRECT = 3;

export const WEBAUTHN_ENTERPRISE_ATTESTATION_NONE = 0;
export const WEBAUTHN_ENTERPRISE_ATTESTATION_VENDOR_FACILITATED = 1;
export const WEBAUTHN_ENTERPRISE_ATTESTATION_PLATFORM_MANAGED = 2;

export const WEBAUTHN_LARGE_BLOB_SUPPORT_NONE = 0;
export const WEBAUTHN_LARGE_BLOB_SUPPORT_REQUIRED = 1;
export const WEBAUTHN_LARGE_BLOB_SUPPORT_PREFERRED = 2;

export const WEBAUTHN_CTAP_TRANSPORT_USB = 0x0000_0001;
export const WEBAUTHN_CTAP_TRANSPORT_NFC = 0x0000_0002;
export const WEBAUTHN_CTAP_TRANSPORT_BLE = 0x0000_0004;
export const WEBAUTHN_CTAP_TRANSPORT_TEST = 0x0000_0008;
export const WEBAUTHN_CTAP_TRANSPORT_INTERNAL = 0x0000_0010;
export const WEBAUTHN_CTAP_TRANSPORT_HYBRID = 0x0000_0020;
export const WEBAUTHN_CTAP_TRANSPORT_SMART_CARD = 0x0000_0040;
export const WEBAUTHN_CTAP_TRANSPORT_FLAGS_MASK = 0x0000_007f;

export const WEBAUTHN_COSE_ALGORITHM_ECDSA_P256_WITH_SHA256 = -7;
export const WEBAUTHN_COSE_ALGORITHM_ECDSA_P384_WITH_SHA384 = -35;
export const WEBAUTHN_COSE_ALGORITHM_ECDSA_P521_WITH_SHA512 = -36;
export const WEBAUTHN_COSE_ALGORITHM_RSASSA_PKCS1_V1_5_WITH_SHA256 = -257;
export const WEBAUTHN_COSE_ALGORITHM_RSASSA_PKCS1_V1_5_WITH_SHA384 = -258;
export const WEBAUTHN_COSE_ALGORITHM_RSASSA_PKCS1_V1_5_WITH_SHA512 = -259;
export const WEBAUTHN_COSE_ALGORITHM_RSA_PSS_WITH_SHA256 = -37;
export const WEBAUTHN_COSE_ALGORITHM_RSA_PSS_WITH_SHA384 = -38;
export const WEBAUTHN_COSE_ALGORITHM_RSA_PSS_WITH_SHA512 = -39;

export const WEBAUTHN_CREDENTIAL_TYPE_PUBLIC_KEY = 'public-key';

export const WEBAUTHN_HASH_ALGORITHM_SHA_256 = 'SHA-256';
export const WEBAUTHN_HASH_ALGORITHM_SHA_384 = 'SHA-384';
export const WEBAUTHN_HASH_ALGORITHM_SHA_512 = 'SHA-512';

export const WEBAUTHN_ATTESTATION_DECODE_NONE = 0;
export const WEBAUTHN_ATTESTATION_DECODE_COMMON = 1;

export const WEBAUTHN_ATTESTATION_TYPE_PACKED = 'packed';
export const WEBAUTHN_ATTESTATION_TYPE_U2F = 'fido-u2f';
export const WEBAUTHN_ATTESTATION_TYPE_TPM = 'tpm';
export const WEBAUTHN_ATTESTATION_TYPE_NONE = 'none';
export const WEBAUTHN_ATTESTATION_VER_TPM_2_0 = '2.0';

export const WEBAUTHN_CREDENTIAL_HINT_SECURITY_KEY = 'security-key';
export const WEBAUTHN_CREDENTIAL_HINT_CLIENT_DEVICE = 'client-device';
export const WEBAUTHN_CREDENTIAL_HINT_HYBRID = 'hybrid';

export const WEBAUTHN_CRED_LARGE_BLOB_OPERATION_NONE = 0;
export const WEBAUTHN_CRED_LARGE_BLOB_OPERATION_GET = 1;
export const WEBAUTHN_CRED_LARGE_BLOB_OPERATION_SET = 2;
export const WEBAUTHN_CRED_LARGE_BLOB_OPERATION_DELETE = 3;

export const WEBAUTHN_CRED_LARGE_BLOB_STATUS_NONE = 0;
export const WEBAUTHN_CRED_LARGE_BLOB_STATUS_SUCCESS = 1;
export const WEBAUTHN_CRED_LARGE_BLOB_STATUS_NOT_SUPPORTED = 2;
export const WEBAUTHN_CRED_LARGE_BLOB_STATUS_INVALID_DATA = 3;
export const WEBAUTHN_CRED_LARGE_BLOB_STATUS_INVALID_PARAMETER = 4;
export const WEBAUTHN_CRED_LARGE_BLOB_STATUS_NOT_FOUND = 5;
export const WEBAUTHN_CRED_LARGE_BLOB_STATUS_MULTIPLE_CREDENTIALS = 6;
export const WEBAUTHN_CRED_LARGE_BLOB_STATUS_LACK_OF_SPACE = 7;
export const WEBAUTHN_CRED_LARGE_BLOB_STATUS_PLATFORM_ERROR = 8;
export const WEBAUTHN_CRED_LARGE_BLOB_STATUS_AUTHENTICATOR_ERROR = 9;

export const WEBAUTHN_EXTENSIONS_IDENTIFIER_HMAC_SECRET = 'hmac-secret';
export const WEBAUTHN_EXTENSIONS_IDENTIFIER_CRED_PROTECT = 'credProtect';
export const WEBAUTHN_EXTENSIONS_IDENTIFIER_CRED_BLOB = 'credBlob';
export const WEBAUTHN_EXTENSIONS_IDENTIFIER_MIN_PIN_LENGTH = 'minPinLength';

export const WEBAUTHN_AUTHENTICATOR_HMAC_SECRET_VALUES_FLAG = 0x0010_0000;

export const WEBAUTHN_MAX_USER_ID_LENGTH = 64;
export const WEBAUTHN_CTAP_ONE_HMAC_SECRET_LENGTH = 32;

export type LPCGUID = Pointer;
export type LPGUID = Pointer;
export type LPPWEBAUTHN_ASSERTION = Pointer;
export type LPPWEBAUTHN_CREDENTIAL_ATTESTATION = Pointer;
export type LPPWEBAUTHN_CREDENTIAL_DETAILS_LIST = Pointer;
export type PCBYTE = Pointer;
export type PCWEBAUTHN_AUTHENTICATOR_GET_ASSERTION_OPTIONS = Pointer;
export type PCWEBAUTHN_AUTHENTICATOR_MAKE_CREDENTIAL_OPTIONS = Pointer;
export type PCWEBAUTHN_CLIENT_DATA = Pointer;
export type PCWEBAUTHN_COSE_CREDENTIAL_PARAMETERS = Pointer;
export type PCWEBAUTHN_GET_CREDENTIALS_OPTIONS = Pointer;
export type PCWEBAUTHN_RP_ENTITY_INFORMATION = Pointer;
export type PCWEBAUTHN_USER_ENTITY_INFORMATION = Pointer;
export type PCWSTR = Pointer;
export type PWEBAUTHN_ASSERTION = bigint;
export type PWEBAUTHN_CREDENTIAL_ATTESTATION = bigint;
export type PWEBAUTHN_CREDENTIAL_DETAILS_LIST = bigint;
